README.md

lernajs.io is not a working domain. Updated the README to show https://lerna.js.org/ instead
See: https://github.com/lerna/lerna#readme-badge

Fixed link for lerna

---

packages/fuselage/webpack.config.js

For some distraction `style-loader` was used instead of `style-loader/useable`.

fix: Webpack rule for CSS

---

packages/fuselage/src/components/Icon/index.js
packages/fuselage/webpack.config.js

1. `React` was declared as an external AMD dependency instead of `react`;
2. Some build systems prefer `.mjs` over `.js` without proper parsing;
3. `MiniCssExtractPlugin.loader` cannot be used with `'style-loader'` in the same chain (see https://github.com/webpack-contrib/mini-css-extract-plugin#advanced-configuration-example)

fix: Bundle errors

---

.circleci/config.yml

Publishes `@rocket.chat/<package name>@next` versions from `develop` branch.

chore(npm): Add CI job to publish a `next` version of packages

---

packages/fuselage-hooks/rollup.config.js

Meteor doesn't handle ES modules yet...

fix: Change bundle format of fuselage-hooks

---

packages/fuselage-hooks/src/useDebouncedCallback.js

As `useCallback`, `useDebouncedCallback` hook should ignore `callback` parameter changes to be memoized.

fix: useDebouncedCallback deps

---

packages/fuselage/src/components/Accordion/Item.js

Oopsie! `Accordion.Item` was ignoring the `className` prop.

fix: Accordion.Item className prop

---

packages/fuselage/src/components/InputControl/styles.js

The user-agent stylesheet of Firefox adds a red shadow to invalid inputs.

fix: Explicitly remove box-shadow for InputBox in Firefox

---

packages/fuselage/.storybook/webpack.config.js

Remove `cssnano` on PostCSS for Storybook to increase CSS readability for debugging.

chore: Don't minify CSS on Storybook

---

packages/fuselage/package.json

Avoiding some annoying warnings about the missing `.storybook/jest-results.json` file.

chore: Jest results

---

packages/fuselage-ui-kit/src/Button.js
packages/fuselage-ui-kit/src/Input.js
packages/fuselage-ui-kit/src/MultiSelect.js
packages/fuselage-ui-kit/src/Overflow.js
packages/fuselage-ui-kit/src/StaticSelect.js
packages/fuselage-ui-kit/src/UIKitModal.stories.mdx
packages/fuselage-ui-kit/src/hooks.js
packages/fuselage-ui-kit/src/index.js
packages/ui-kit/src/index.ts

if we do not use as a components we have problems with contexts and hooks

fix: uikit using react components

---

packages/fuselage-ui-kit/webpack.config.js
packages/fuselage/webpack.config.js
packages/ui-kit/webpack.config.js

Under restricted CSP, `eval()` calls are forbidden. This PR removes source maps from production builds and adds regular ones to development builds.

fix: Replace eval-based source maps

---

packages/fuselage/src/components/Box/Scrollable/index.js

Scrollable now accepts scrollCb that receives `{ top: bool, bottom: bool, left: bool, right: bool}`.
The condition for each boolean is that content is hidden in that direction (eg. if scrolled down, top will be true).

feat: Added callback prop for scroll position

---

packages/css-in-js/package.json
packages/css-in-js/rollup.config.js
packages/fuselage/package.json

For some reason Webpack throws warnings about ignoring CommonJS exports. This seems to fix it.

fix: Build @rocket.chat/css-in-js as ES module

---

packages/fuselage/src/components/Select/Select.js

Changed the options object that was sent to the _Options in the Select.js file. Please let me know if the issues need to be resolved in any other places as well and I will do so accordingly.
fixes issue #162

fix: SelectFiltered: Wrong keyboard navigation

---

packages/fuselage/src/components/CheckBox/index.js
packages/fuselage/src/components/RadioButton/index.js
packages/fuselage/src/components/ToggleSwitch/index.js

As we visually replace checkboxes and radio buttons with our implementation, the component props must be shared between the container element and the real input element.

fix: Selection button props split between container and input elements

---

packages/fuselage/src/styles/colors.scss

Some CSS custom properties were wrongly named.

fix: CSS custom property name interpolation

---

packages/fuselage/src/styles/props/special.js

An invalid value was assigned.

regression: ul and ol padding

---

packages/mp3-encoder/package.json
packages/mp3-encoder/rollup.config.js
yarn.lock

The `lamejs` isn't published in npmjs.com since 2017 and it wasn't bundled for modular use. As result, our package was presenting the same issues reported in https://github.com/RocketChat/Rocket.Chat/issues/10530 (thanks @rkramer1964 for [solution](https://github.com/RocketChat/Rocket.Chat/issues/10530#issuecomment-462843092)). We should replace it in the future with the MediaRecorder API.

fix: lamejs problematic usage

---

packages/fuselage-hooks/package.json

It looks like Jest devours CircleCI runner memory with its many workers. Let's see if it fixes it.

chore: Use a single Jest worker

---

packages/fuselage-hooks/src/useMediaQueries.ts

As seen in https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener:
> This is basically an alias for EventTarget.addEventListener(), for backwards compatibility purposes. Older browsers should use addListener instead of addEventListener since MediaQueryList only inherits from EventTarget in newer browsers.
`MediaQueryList` don't inherits from `EventTarget` in [Safari and IE11](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#Browser_compatibility). This PR fallbacks to `addListener`/`removeListener` when `addEventListener`/`removeEventListener` aren't present.

fix: useMediaQueries support on Safari and IE11

---

packages/fuselage/src/styles/mixins/states.scss

The :focus-visible selector has been causing some problems and in an effort to keep usability, it'll be disabled 'till we review this.

fix: Disable :focus-visible for the time being

---

packages/css-in-js/src/transpile/border-radius.spec.ts
packages/css-in-js/src/transpile/border.spec.ts
packages/css-in-js/src/transpile/inset.spec.ts
packages/css-in-js/src/transpile/logicalProperties.ts
packages/css-in-js/src/transpile/margin.spec.ts
packages/css-in-js/src/transpile/padding.spec.ts
packages/fuselage/src/components/Margins/spec.js

The selector `*:not([dir=rtl])` will style elements even under an ancestor with `dir="rtl"` if some descendant ancestors don't declare the `dir` attribute. The current workaround is to just use the attribute at the `documentElement`, i.e., the `html` element.

fix: Use dir attribute from documentElement

---

packages/fuselage-ui-kit/webpack.config.js
packages/fuselage/webpack.config.js
packages/ui-kit/.eslintignore
packages/ui-kit/webpack.config.js
yarn.lock

It should get rid of ES2015 syntax on Webpack support code in bundles.

fix: Set a conservative output.environment on Webpack bundles

---

packages/fuselage/src/components/Field/styles.scss

This was breaking the fields on safari
Companion PR of https://github.com/RocketChat/Rocket.Chat/pull/19671

fix: Flex-shrink on fields

---

packages/fuselage/src/components/Sidebar/styles.scss

fix: Sidebar menu cropped in extended mode

---

packages/fuselage/src/components/Sidebar/styles.scss

fix: Change highlighted style

---

packages/fuselage-hooks/src/index.ts
packages/fuselage-hooks/src/usePrevious.spec.ts
packages/fuselage-hooks/src/usePrevious.ts

`usePrevious()` might be useful as a complement for effects where you need to track _how_ a value have changed.

feat: usePrevious hook

---

packages/fuselage/index.js

fix(fuselage): Fuselage production build

---

packages/icons/README.md

chore: Update icon building readme

---

packages/onboarding-ui/src/forms/CreateNewPassword/CreateNewPassword.tsx
packages/onboarding-ui/src/forms/ResetPasswordForm/ResetPasswordForm.tsx

fix: add mode on change on request reset password
fix: add mode on change on create password form

fix: add mode on change in forms

---

packages/onboarding-ui/src/forms/RequestTrialForm/RequestTrialForm.tsx

feat: add 2 new checkboxes to confirm terms and conditions and for users keep informed about the news.

feat: request trial checkbox terms conditions

---

packages/fuselage/src/components/CodeSnippet/styles.scss

- Added a word-break property to the codebox class;
- Added margin-right property to the codebox class;
The codebox class div was breaking with big words in small screens

fix(fuselage): CodeSnippet word-break

---

packages/fuselage/src/components/SelectPaginated/PaginatedSelect.stories.tsx
packages/fuselage/src/components/SelectPaginated/PaginatedSelectFiltered.tsx

It makes `onChange` prop to be consumed instead of ignored.

fix(fuselage): `onChange` prop on `PaginatedSelectFiltered`

---

packages/fuselage/src/components/Message/MessageEmoji.tsx
packages/fuselage/src/components/Message/MessageEmojiBase.tsx
packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.stories.tsx
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.styles.scss
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessageEmoji.tsx
packages/fuselage/src/components/Message/ThreadMessage/index.tsx
packages/fuselage/src/components/Message/index.tsx

feat(fuselage): MessageEmoji and ThreadMessageEmoji components

---

packages/fuselage/src/components/Message/MessageReactions/MessageReactions.styles.scss
packages/fuselage/src/components/Message/MessageReactions/MessageReactions.tsx
packages/fuselage/src/components/Message/Messages.stories.tsx

fix(fuselage): Reaction list not wrapping

---

packages/layout/src/FormPageLayout/FormPageLayout.styles.tsx

Change font weight on FormPageLayout according to Figma.
[https://rocketchat.atlassian.net/browse/CS-64](https://rocketchat.atlassian.net/browse/CS-64)

chore: change font weight on FormPageLayout according to figma

---

packages/fuselage/src/components/Banner/Banner.spec.tsx
packages/fuselage/src/components/Banner/Banner.stories.js
packages/fuselage/src/components/Banner/Banner.styles.scss
packages/fuselage/src/components/Banner/Banner.tsx

Add link property to banner according to new figma designs.
Banner without link:
Banner with link:
[https://rocketchat.atlassian.net/browse/CS-131](https://rocketchat.atlassian.net/browse/CS-131)

feat: Add link property to banner component

---

packages/fuselage/src/components/Box/props.stories.mdx
packages/fuselage/src/components/Box/stylingProps.ts

feat(fuselage): Adds wordbreak in Box Component

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/inlineCode.test.ts

TC-104
**Problem:**
Some combinations of inline code with back-stick was resulting in a plain text, the root cause is because the back-stick was being considered a valid character that should be in the Domain Name of an URL
**Solution:**
Was added a back-stick char into the invalid chars to parse an URL domain name.
**Current behavior**
**Expected behavior**

fix(message-parser): Backtick char in domainChar

---

packages/fuselage/src/components/Message/MessageToolbox/MessageToolbox.styles.scss
yarn.lock

fix(fuselage): Message Toolbox margin

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/src/utils.ts
packages/message-parser/tests/phoneNumber.test.ts

The  Phone code matches any plus sign (+) followed by one or more digits, regardless of whether it is a valid phone number.
To fix this behavior we are now checking if the phone number has any other characters other than `(`, `)` and `-` and at least 5 numbers 
In a chat, enter the text 1+1=2
The chat message should not contain any hyperlinks
other e.g:
The +1 is hyperlinked to tel:1 even though it is not a valid phone number.
Other e.g:
https://github.com/RocketChat/Rocket.Chat/issues/27141
TC-250

fix(message-parser): Phone pattern 

---

packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss

Today the message heading are displayed as normal texts, with the same size, and style. 
To fix this behavior and make to behave as the previous message parser we added the typography tokens from `fuselage-tokens` to the scss file responsible for message styles.
TC-273

fix(fuselage): Adding heading tag styles to messages

---

packages/fuselage/src/components/Modal/Modal.styles.scss
packages/fuselage/src/components/Modal/ModalContent.tsx

Right now we don't have fallback styles for `margin-inline` compatible with older browsers.
styles in safari 14:

refactor(fuselage): Move margin inline style to inline box at `Modal`

---

packages/fuselage/src/components/Message/Messages.styles.scss

The CSS added into `rcx-message-body` `word-break: break-all;` was breaking a word in the middle in the messages.
To change this behavior and break the entire word I changed to `word-break: break-word;`
**Previous**
**NOW**

fix(fuselage): word break in rcx-message-body

---

packages/fuselage/src/components/Tag/Tag.styles.scss

chore(fuselage): Remove fit-content width from `Tag`

---

packages/fuselage/src/components/Message/Messages.styles.scss

- set link's color inside messages with the correct token: `font-info`
- not all message links were using the correct token, inheriting the default color for `<a>` (e.g on threads list)
from:
to:

fix(fuselage): message link color

---

packages/fuselage/src/components/Menu/V2/Menu.tsx

chore(fuselage): `MenuV2` expose pressed prop

---

packages/emitter/src/emitter.spec.ts
packages/emitter/src/index.ts

For any `Emitter` instance, if there is only one event handler attached to some event `x`, calling `emitter.off('x', handler)` will wipe that handler regardless of `handler` being the one.
```ts
it('should remove only the specified handler', () => {
const handler = jest.fn();
const unusedHandler = jest.fn();
emitter.on('test', handler);
emitter.off('test', unusedHandler);
emitter.emit('test');
expect(handler).toHaveBeenCalledTimes(1); // Actual: 0
expect(unusedHandler).toHaveBeenCalledTimes(0);
});
```

fix(emitter): `off()` ignoring handler check when one listener remains

---

packages/fuselage/.jest/setup.ts
packages/fuselage/src/components/Accordion/Accordion.spec.tsx
packages/fuselage/src/components/Button/Button.spec.tsx
packages/fuselage/src/components/Button/Button.stories.tsx
packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/Button.tsx
packages/fuselage/src/components/Button/IconButton.tsx
packages/fuselage/src/components/ButtonGroup/ButtonGroup.spec.tsx
packages/fuselage/src/components/CheckBox/CheckBox.spec.tsx
packages/fuselage/src/components/Field/Field.spec.tsx
packages/fuselage/src/components/Label/Label.spec.tsx
packages/fuselage/src/components/Table/Table.spec.tsx
packages/fuselage/src/components/ToastBar/ToastBar.spec.tsx

- change `Button` default size to 40px

chore(fuselage): `Button` size

---

packages/fuselage/src/components/Modal/Modal.spec.tsx
packages/fuselage/src/components/Modal/Modal.stories.tsx
packages/fuselage/src/components/Modal/Modal.tsx
packages/fuselage/src/components/Modal/ModalTitle.tsx
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap

chore(fuselage): `Modal` a11y improvements

---

packages/fuselage-hooks/src/index.ts
packages/fuselage-hooks/src/useElementIsVisible.ts

feat: create useElementIsVisible

---

packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/IconButton.stories.tsx

- adjust mixin `click-animation` selector to ignore status badges

fix(fuselage): `IconButton` with badge click-animation

---

packages/fuselage/src/components/AudioPlayer/AudioPlayer.tsx

The issue is that some kind of audio files are not returning the correct duration with metaData, they are returning `Infinity` which is crashing the UI.
So this is a common issue and we have a few workarounds for solving this - 
1. Fetch the entire file in background and then get the duration. Didn't use this approach as it would unnecessarily download(fetch) the entire file.
2. Seek the audio element to play some audio by setting the `currentTime` of the element, set this `currentTime` to some very big number, which will cause it to fetch the real duration of the audio file and then we can use this duration. I've used this approach, but I ran into another issue when using this approach. After setting the `currentTime` to a very big number, the audio element was breaking for no apparent …

fix(fuselage): `AudioPlayer`: `Infinity` duration audio files crashing

---

.changeset/thin-candles-doubt.md
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.tsx

fix(fuselage): `PaginatedSelect` tooltip not working

---

.changeset/twelve-yaks-study.md
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelect.tsx

feat(fuselage): Add `renderItem` prop to the `PaginatedMultiSelect` component

---

.changeset/quiet-pigs-peel.md
packages/fuselage/src/components/Callout/Callout.styles.scss
packages/fuselage/src/components/Callout/Callout.tsx
packages/fuselage/src/components/Callout/__snapshots__/Callout.spec.tsx.snap

fix(fuselage): add `Callout` missing background-color

---

.changeset/cyan-pots-care.md
packages/message-parser/src/definitions.ts

Added ChannelMention in the type Markup
- I have read the Contributing Guide - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat doc
- I have signed the CLA - https://cla-assistant.io/RocketChat/Rocket.Chat
- Lint and unit tests pass locally with my changes
- I have labeled the PR correctly with the related package
- Any dependent changes have been merged and published in downstream modules
Initially, the bold, strike, and italic markup was not working on the mobile while mentioning the channel name in the message box.
I have made the necessary changes in the React Native repo but there is a specific change that is required in the fuselage repo as well for that change to work. We need to add ChannelMention in the type Markup for this …

fix(message-parser): Added ChannelMention in the markup

---

.changeset/sharp-planets-type.md
.husky/pre-commit
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx

Sometimes we need to send the `onBlur` event as prop to the `AutoComplete` component which overrides the already implemented `onBlur` event which is used to hide the suggestions box, due to which the suggestions are not hiding after moving away from the component.
TC-1030

fix(fuselage): Handle `onBlur` prop on AutoComplete

---

.changeset/old-taxis-boil.md
packages/fuselage/src/components/CheckBox/CheckBox.tsx
packages/fuselage/src/components/CheckBox/__snapshots__/CheckBox.spec.tsx.snap
packages/fuselage/src/components/Field/Field.stories.tsx
packages/fuselage/src/components/Field/Field.styles.scss
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/RadioButton/RadioButton.tsx
packages/fuselage/src/components/RadioButton/__snapshots__/RadioButton.spec.tsx.snap
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.tsx
packages/fuselage/src/components/ToggleSwitch/__snapshots__/ToggleSwitch.spec.tsx.snap

[DSAR-319]
[DSAR-319]: https://rocketchat.atlassian.net/browse/DSAR-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): `FieldLabel` margins and paddings

---

.changeset/ninety-turkeys-happen.md
packages/fuselage/src/components/Bubble/Bubble.spec.tsx
packages/fuselage/src/components/Bubble/Bubble.stories.tsx
packages/fuselage/src/components/Bubble/Bubble.styles.scss
packages/fuselage/src/components/Bubble/Bubble.tsx
packages/fuselage/src/components/Bubble/__snapshots__/Bubble.spec.tsx.snap
packages/fuselage/src/components/Bubble/index.ts
packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/index.scss
packages/fuselage/src/components/index.ts
packages/fuselage/src/styles/lengths.scss
packages/fuselage/src/styles/mixins/interactivity.scss
packages/fuselage/src/styles/primitives/button.scss

[DSAR-380](https://rocketchat.atlassian.net/browse/DSAR-380)
[DSAR-380]: https://rocketchat.atlassian.net/browse/DSAR-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): new `Bubble` component

---

packages/fuselage/src/components/Button/Button.stories.tsx
packages/fuselage/src/components/ButtonGroup/ButtonGroup.tsx
packages/fuselage/src/components/Modal/ModalFooterControllers.tsx
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap
packages/fuselage/src/components/States/StatesActions.tsx
packages/onboarding-ui/src/forms/AdminInfoForm/AdminInfoForm.tsx
packages/onboarding-ui/src/forms/CreateNewPassword/CreateNewPassword.tsx
packages/onboarding-ui/src/forms/NewAccountForm/NewAccountForm.tsx
packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx
packages/onboarding-ui/src/forms/RegisterOfflineForm/steps/CopyStep.tsx
packages/onboarding-ui/src/forms/RegisterOfflineForm/steps/PasteStep.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx
packages/onboarding-ui/src/forms/ResetPasswordForm/ResetPasswordForm.tsx

feat(fuselage): Avoid `Box` usage on `ButtonGroup`

---

.changeset/cold-students-shop.md
packages/fuselage/src/components/ButtonGroup/ButtonGroup.tsx

fix(fuselage): `ButtonGroup` missing `className` exposure

---

.changeset/wise-poems-shop.md
packages/fuselage/src/components/Message/MessageNameContainer.tsx

fix(fuselage): `MessageNameContainer` missing forwardRef

---

packages/fuselage-hooks/src/usePosition/index.ts

chore(fuselage-hooks): increase `usePosition` zIndex

---

.changeset/metal-ravens-hug.md
packages/fuselage/src/components/Message/Messages.styles.scss

feat(fuselage): Add focus state on `MessageHighlight`

---

.changeset/sour-pumpkins-repeat.md
packages/fuselage/src/components/Accordion/Accordion.styles.scss

Change token color affecting dark mode for the accordion component, requested by design. 
It doesn't affect light mode.
Before:
After: 
[https://rocketchat.atlassian.net/browse/CORE-36](https://rocketchat.atlassian.net/browse/CORE-36)

fix(fuselage): border color on accordion component

---

.changeset/clever-socks-double.md
packages/fuselage/src/components/ToastBar/ToastBar.tsx

fix(fuselage): `ToastBar` remove close button from content alert

---

.changeset/angry-avocados-punch.md
packages/fuselage/src/components/Message/MessageMetrics/MessageMetrics.spec.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetrics.stories.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetricsContent.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetricsContentItem.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetricsFollowing.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetricsItem/MessageMetricsItemLabel.tsx
packages/fuselage/src/components/Message/MessageMetrics/MessageMetricsItem/index.ts
packages/fuselage/src/components/Message/MessageMetrics/__snapshots__/MessageMetrics.spec.tsx.snap
packages/fuselage/src/components/Message/MessageMetrics/index.tsx
packages/fuselage/src/components/Message/helpers.tsx

fix(fuselage): `MessageMetrics` props types

---

.changeset/smart-cars-jog.md
packages/fuselage/src/components/Message/MessageMetrics/index.tsx

fix(fuselage): `MessageMetrics` being exported incorrectly

---

.changeset/wild-camels-relax.md
packages/fuselage/src/components/Message/MessageReactions/MessageReactions.styles.scss
packages/fuselage/src/styles/mixins/templates.scss

fix(fuselage): `MessageReactions` missing border color

---

.changeset/kind-turkeys-relate.md
packages/layout/src/FormPageLayout/FormContainer.tsx
packages/layout/src/FormPageLayout/index.ts

fix(layout): `FormContainer` wrong props

---

.changeset/rotten-melons-smash.md
packages/fuselage/src/components/InputBox/InputBox.styles.scss

[SIDE-83](https://rocketchat.atlassian.net/browse/SIDE-83)
[SIDE-83]: https://rocketchat.atlassian.net/browse/SIDE-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): decrease `InputBox` small inline paddings

---

.changeset/stale-boats-collect.md
packages/fuselage/src/components/Contextualbar/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/ContextualbarV2/Contextualbar.spec.tsx
packages/fuselage/src/components/ContextualbarV2/Contextualbar.stories.tsx
packages/fuselage/src/components/ContextualbarV2/Contextualbar.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarAction.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarActions.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarButton.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarContent.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarEmptyContent.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarFooter.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarHeader.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarIcon.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarSection.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarSkeleton.tsx
packages/fuselage/src/components/ContextualbarV2/ContextualbarTitle.tsx
packages/fuselage/src/components/ContextualbarV2/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/ContextualbarV2/index.ts
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Sidebar/TopBar/TopBarV2.tsx
packages/fuselage/src/components/Sidebar/TopBar/index.ts
packages/fuselage/src/components/index.ts

The changes of the PRs below need to be moved into a V2 folder to support both versions until final deprecation
#1366 
#1369

fix(fuselage): move size changes into V2 components

---

.changeset/clever-candles-shop.md
packages/fuselage/src/components/Table/Table.spec.tsx
packages/fuselage/src/components/Table/Table.stories.tsx
packages/fuselage/src/components/Table/Table.styles.scss
packages/fuselage/src/components/Table/Table.tsx
packages/fuselage/src/components/Table/TableSelection/TableSelection.tsx
packages/fuselage/src/components/Table/TableSelection/TableSelectionButton.tsx
packages/fuselage/src/components/Table/TableSelection/TableSelectionButtonGroup.tsx
packages/fuselage/src/components/Table/TableSelection/index.ts
packages/fuselage/src/components/Table/__snapshots__/Table.spec.tsx.snap
packages/fuselage/src/components/Table/index.ts

feat(fuselage): `TableSelection` visual improvements 

---

.changeset/late-glasses-accept.md
packages/fuselage/src/components/Menu/V2/MenuItem.tsx

Fixes Menu triggering pointerUp event immediately when Popover overlaps its Trigger button.
This solution is a workaround suggested on [this issue](https://github.com/adobe/react-spectrum/issues/3864) on react-spectrum

fix(fuselage): `MenuItem` onPointerUp event behavior

---

packages/fuselage-toastbar/.storybook/DocsContainer.tsx
packages/fuselage-toastbar/.storybook/preview.tsx
packages/fuselage-toastbar/package.json
packages/fuselage/.storybook/DocsContainer.tsx
packages/fuselage/.storybook/preview.tsx
packages/layout/.storybook/DocsContainer.tsx
packages/layout/.storybook/preview.tsx
packages/layout/package.json
packages/onboarding-ui/.storybook/DocsContainer.tsx
packages/onboarding-ui/.storybook/preview.tsx
yarn.lock

It fixes dark mode theming in Storybook Docs pages and in canvasses backgrounds.
To do: move the common configuration to a single and unified configuration package.

chore: Broken dark mode in Storybook docs and canvasses

---

.changeset/tasty-planets-travel.md
packages/fuselage/src/components/SidebarV2/Sidebar.styles.scss
packages/fuselage/src/components/SidebarV2/hooks/useCollapse.tsx

fix(fuselage): `useCollapse` expanded prop usage

---

.changeset/soft-islands-decide.md
packages/fuselage/jest-setup.ts
packages/fuselage/src/components/Accordion/Accordion.spec.tsx
packages/fuselage/src/components/Accordion/Accordion.stories.tsx
packages/fuselage/src/components/Accordion/Accordion.styles.scss
packages/fuselage/src/components/Accordion/Accordion.tsx
packages/fuselage/src/components/Accordion/AccordionItem.tsx
packages/fuselage/src/components/Accordion/__snapshots__/Accordion.spec.tsx.snap
packages/fuselage/src/components/Accordion/index.ts
packages/fuselage/src/components/Box/StylingBox.tsx
packages/fuselage/src/components/Box/index.ts
packages/fuselage/src/components/Box/index.tsx
packages/fuselage/src/helpers/composeClassNames.ts
packages/fuselage/src/helpers/exhaustiveCheck.ts

It removes an obsolete and not accessible toggle switch in `AccordionItem` and eases the internal usage of `Box` to
improve rendering performance.
Additionally, it adds a new `StylingBox` component that can be used as a wrapper for components that accept styling
props but don't need the weight of the `Box` component prop handling internally.
Also, it adds a new `cx` and `cxx` helpers to compose class names.
An important tweak was made in Jest's setup, mocking `useUniqueId` calls to return deterministic IDs, allowing snapshot matching.

feat(fuselage)!: Lighter `Accordion` and `AccordionItem` components

---

.changeset/ninety-monkeys-notice.md
packages/mp3-encoder/src/lame/assert.ts

It suppresses assertions at the LAME encoding due to unknown `NaN` values.
This is the original `assert` function: https://github.com/zhuker/lamejs/blob/090eaa9b7e90abb81939145f13be2bdcd06ac5e6/src/js/common.js#L148-L150
During investigation, the input buffers showed a small segment of `NaN` values instead of the expected typed Float32 numbers. It couldn't be determined where they are allocated, because they seen to exist prior to the `flush` call. Since there is no `async` function or callbacks at play (as the original code was transpiled from single-threaded Java code), the hypothesis of `message` events out of sync at the worker thread can be disregarded. One interesting thing to note is that when using a external microphone instead of Macbook's built-in microphone did **not** …

fix(mp3-encoder): Suppress assertion

---

.changeset/hungry-rings-develop.md
packages/fuselage/src/components/Card/Card.styles.scss

Changed the card-vertical-gap to 32px to follow [design specs](https://www.figma.com/design/zASOpMgEuQ11mwaCg0L5py/Subs-%2F-WS-page-QA?node-id=65-683&t=ch4PTIP7E0rF9ciz-4).
Jira task: [CONN-416](https://rocketchat.atlassian.net/browse/CONN-416)
[CONN-416]: https://rocketchat.atlassian.net/browse/CONN-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): Change `Card` vertical-gap to 32px

---

.changeset/eight-birds-invite.md
packages/fuselage-hooks/src/useEffectEvent.ts
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.tsx
packages/fuselage/src/components/Select/SelectLegacy.tsx

It aims to make the generic type constraint of `useEffectEvent` not allow implicit `any` parameters.
[Demonstration](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMAPAFUQUwB5U2AEwGdEAKAOkoEMAnAcyIC5EqwBPAbQF0BKRAXgB8LdoNLZmaPgG8AUIgWIamKCBpJsAblkBfWbIgIiUFgOSlxfIYmw9thsMcQAjZuOZgQAW2eYaV4U8fPzNgC1sBYVttWVBIWAREOnQsXHxiRAAxcGh4MDEJRClEOUUlFTUNbT0DIxMIMzpwgJs7RAB6dsQYLwAHABsYCBgTVjZaxxMCN0Kg339IxDmQ-iTmxeigA)

fix(fuselage-hooks): Stricter generics for `useEffectEvent`

---

.changeset/tall-rabbits-do.md
packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/Option/OptionIcon.tsx

fix(fuselage): `OptionIcon` not receiving proper icon props

---

.changeset/modern-cycles-reflect.md
packages/fuselage/src/components/Select/SelectAria.tsx

fix(fuselage): hidden select should be child of trigger

---

.changeset/grumpy-mice-draw.md
packages/fuselage/src/components/Slider/SliderTrack.tsx

There was a rendering issue with the SliderTrack component in Chromium-based browsers. The component was using the CSS attr() function with an invalid attribute but without specifying fallback values or attribute types. While this edge case should return an empty string according to the CSS specification, Chromium browsers weren't handling it correctly, causing the track to fail to render. This has been fixed by explicitly setting an empty string ('') instead of relying on attr().
Before:
After:

fix(fuselage): Missing track on `Slider` component

---

.changeset/ninety-cherries-pull.md
packages/fuselage/src/hooks/useStyle.ts
packages/styled/src/styled.ts

> useInsertionEffect allows inserting elements into the DOM before any layout Effects fire.
It's indicated for inserting styles before any Effects fire that may need to read layout.
ref: https://react.dev/reference/react/useInsertionEffect
This PR replaces `useLayoutEffect` in favor of `useInsertionEffect` in Box component's `useStyle` hook and in `styled` package.

feat: replace `useLayoutEffect` in favor of `useInsertionEffect`

---

.changeset/social-clubs-switch.md
packages/fuselage/src/components/SidebarV2/Sidebar.styles.scss

[SIDE2-87]
[SIDE2-87]: https://rocketchat.atlassian.net/browse/SIDE2-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): `SidebarItemV2Title` unread bold styles

---

.changeset/gold-dolls-burn.md
packages/fuselage/src/components/Field/FieldLabel.spec.tsx
packages/fuselage/src/components/Field/FieldLabel.tsx
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap
packages/layout/src/layouts/HorizontalWizardLayout/__snapshots__/HorizontalWizardLayout.spec.tsx.snap
packages/layout/src/layouts/VerticalWizardLayout/__snapshots__/VerticalWizardLayout.spec.tsx.snap
packages/onboarding-ui/src/forms/RegisterServerForm/__snapshots__/RegisterServerForm.spec.tsx.snap

This PR fixes a bug where the required `*` indicator was not displayed next to the label text when the `is` prop was provided. This occurred because the is prop was overriding the default `Label` component, which caused its built-in behaviors to be bypassed.
The issue was resolved by removing the intermediate `Box` wrapper and passing all props directly to the `Label` component, which natively supports the `is` prop and preserves the expected functionality.
[CTZ-244](https://rocketchat.atlassian.net/browse/CTZ-244)
This fix is especially useful in cases where using the `htmlFor` attribute is not appropriate, such as when the form field is labeled via ARIA attributes instead. In these scenarios, ensuring HTML compliance may require using a different tag for the label, for example:
```jsx …
```

fix(fuselage): FieldLabel required prop ignored when 'is' prop is set

---

.changeset/fluffy-rats-film.md
packages/fuselage/src/components/AutoComplete/AutoComplete.spec.tsx
packages/fuselage/src/components/AutoComplete/AutoComplete.stories.tsx
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx
packages/fuselage/src/components/AutoComplete/__snapshots__/AutoComplete.spec.tsx.snap

This PR fixes an issue where the `AutoComplete` component did not respect the `disabled` prop when it was set to `true`. This happened because the `disabled` attribute was not being forwarded to the internal `InputBox.Input` component.
The issue was resolved by explicitly passing the `disabled` prop to the `InputBox.Input`, ensuring the input is properly disabled.
[CTZ-244](https://rocketchat.atlassian.net/browse/CTZ-244)
[CTZ-244]: https://rocketchat.atlassian.net/browse/CTZ-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): AutoComplete's disabled property not working

---

.changeset/twenty-bobcats-cover.md
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.spec.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedSelectFiltered.spec.tsx
packages/fuselage/src/components/PaginatedSelect/__snapshots__/PaginatedSelectFiltered.spec.tsx.snap

This PR fixes a bug in the `PaginatedSelect` that was affecting only `PaginatedSelectFiltered`. The bug prevented the placeholder from being displayed in the `PaginatedSelectFiltered` due incorrect visible text check, causing the anchor to be hidden when not focused. The issue was fixed by adjusting the visibility check. Unit tests were also added to prevent this issue from happening again.
Note: classNames were used in the tests due to the select styles not being properly computed in the `PaginatedSelectFiltered` unit tests.
This PR fixes a bug in `PaginatedSelect` that was affecting `PaginatedSelectFiltered`, where the placeholder was not displayed due to an incorrect visible text check. As a result, the anchor element was hidden when the select was not focused. The issue has been …

fix(fuselage): Placeholder not being displayed in PaginatedSelectFiltered

---

.changeset/swift-llamas-wait.md
packages/fuselage-hooks/src/useStorage.ts

It exposes the `useStorage` hook as an alternative for the specialized ones (`useLocalStorage` and `useSessionStorage`).

feat(fuselage-hooks): Expose `useStorage`

---

.changeset/green-walls-kick.md
packages/fuselage/src/components/AutoComplete/AutoComplete.spec.tsx
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx

Previously, selected items in the AutoComplete component could remain visible even when the current value no longer contained them. This PR adds a validation step to ensure consistency between the value and the selected items, removing any invalid ones.
[CTZ-336](https://rocketchat.atlassian.net/browse/CTZ-336)
[CTZ-336]: https://rocketchat.atlassian.net/browse/CTZ-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): AutoComplete selected items not being updated when value changes

---

.changeset/five-pillows-agree.md
packages/fuselage-hooks/src/useStorage.ts

It ensures that the function type of `useLocalStorage` and `useSessionStorage` has a generic parameter.
`Function.prototype.bind` erases generic parameters due to inference.

fix(fuselage-hooks): Preserve generic type of `useLocalStorage` and `useSessionStorage`

---

.changeset/empty-snails-peel.md
packages/fuselage-forms/README.md
packages/fuselage-forms/package.json
packages/fuselage-forms/src/Field/FieldContext.ts
packages/fuselage-forms/src/Field/FieldProvider.tsx
packages/fuselage-forms/src/Inputs/withLabelHelpers.tsx
packages/fuselage-forms/src/test.spec.tsx
packages/fuselage-hooks/src/useSafeRefCallback/useSafeRefCallback.ts
yarn.lock

[ARCH-1783](https://rocketchat.atlassian.net/browse/ARCH-1783)
[ARCH-1783]: https://rocketchat.atlassian.net/browse/ARCH-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage-forms): Clicking on label does not focus on the input
