RocketChat/fuselage

CHANGELOG.md
lerna.json
packages/fuselage-hooks/CHANGELOG.md
packages/fuselage-hooks/package.json
packages/fuselage-tokens/CHANGELOG.md
packages/fuselage-tokens/package.json
packages/fuselage/CHANGELOG.md
packages/fuselage/package.json
packages/fuselage/src/components/FieldGroup/styles.scss
packages/icons/CHANGELOG.md
packages/icons/package.json
yarn.lock

This should fix some issues with `Callout` width on Rocket.Chat's Administration pages.

fix: Remove FieldGroup minimum width

---

packages/fuselage-ui-kit/src/Input.js
packages/fuselage-ui-kit/src/UIKitModal.stories.mdx
packages/fuselage-ui-kit/src/index.js

feat: UiKit error states

---

packages/fuselage-hooks/.jest/helpers.js
packages/fuselage-hooks/README.md
packages/fuselage-hooks/package.json
packages/fuselage-hooks/src/index.js
packages/fuselage-hooks/src/useMutableCallback.js
packages/fuselage-hooks/tests/useClassName.spec.js
packages/fuselage-hooks/tests/useDebouncedCallback.spec.js
packages/fuselage-hooks/tests/useDebouncedUpdates.spec.js
packages/fuselage-hooks/tests/useExclusiveBooleanProps.spec.js
packages/fuselage-hooks/tests/useMediaQuery.spec.js
packages/fuselage-hooks/tests/useMergedRefs.spec.js
packages/fuselage-hooks/tests/useMutableCallback.spec.js
packages/fuselage-hooks/tests/useToggle.spec.js
packages/fuselage-hooks/tests/useUniqueId.spec.js

Porting a hook I've implemented on Rocket.Chat codebase.

feat: useMutableCallback

---

README.md

I just tried to proofread the README and improve on any possible grammar. Please merge if you think it is helpful.

fixed grammer in README

---

packages/fuselage-ui-kit/src/Input.js

Fixed modalblock input render.

fix: Spacing and markup in Ui Kit inputs

---

.circleci/config.yml
packages/fuselage/package.json

Skipping Jest tests in Storybook when running Loki tests.

chore: Fix Storybook test and build

---

packages/fuselage/src/styles/primitives/box.scss

Forces default flexbox properties to overcome known bugs.

fix: Force default flex properties on Box styles

---

packages/fuselage-hooks/README.md
packages/fuselage-hooks/src/helpers.js
packages/fuselage-hooks/src/index.js
packages/fuselage-hooks/src/useAutoFocus.js
packages/fuselage-hooks/src/useDebouncedCallback.js
packages/fuselage-hooks/src/useDebouncedUpdates.js
packages/fuselage-hooks/src/useResizeObserver.js
packages/fuselage-hooks/tests/useResizeObserver.server.spec.js
packages/fuselage-hooks/tests/useResizeObserver.spec.js

Hook to track dimension changes in a DOM element using the ResizeObserver API.

feat: useResizeObserver

---

packages/fuselage/src/components/InputBox/styles.scss

Reverts RocketChat/Rocket.Chat.Fuselage#225

Revert "fix: Input box flex"

---

packages/fuselage/package.json
packages/fuselage/src/helpers/memoize.js
packages/fuselage/src/styles/helpers.js
packages/fuselage/src/styles/props/borders.js
packages/fuselage/src/styles/props/colors.js
packages/fuselage/src/styles/props/layout.js
packages/fuselage/src/styles/props/position.js
packages/fuselage/src/styles/props/spaces.js
yarn.lock

This should get rid of an incompatibility with IE11 also.

perf: Replace `mem` with a simpler memoization decorator

---

packages/fuselage/src/components/Box/index.js
packages/fuselage/src/components/Box/spec.js

`Box` was not transforming an empty array into a string to be set to the `className` prop.

fix: Box className prop

---

packages/fuselage-hooks/README.md
packages/fuselage-hooks/jest.config.js
packages/fuselage-hooks/package.json
packages/fuselage-hooks/src/__mocks__/matchMedia.ts
packages/fuselage-hooks/src/index.ts
packages/fuselage-hooks/src/useBreakpoints.spec.ts
packages/fuselage-hooks/src/useBreakpoints.ts
packages/fuselage-hooks/src/useMediaQueries.server.spec.ts
packages/fuselage-hooks/src/useMediaQueries.spec.ts
packages/fuselage-hooks/src/useMediaQueries.ts
packages/fuselage-hooks/src/useMediaQuery.server.spec.ts
packages/fuselage-hooks/src/useMediaQuery.spec.ts
packages/fuselage-hooks/src/useMediaQuery.ts
packages/fuselage-hooks/src/useStableArray.spec.ts
packages/fuselage-hooks/src/useStableArray.ts
packages/fuselage-hooks/tsconfig.json
packages/fuselage-tokens/breakpoints.json
yarn.lock

It adds media queries-related hooks:
- `useBreakpoints`;
- `useMediaQueries`.
Also, `useStableArray` was added to provide better ergonomics for arrays as dependency of effects.

feat: useStableArray, useBreakpoints, useMediaQueries

---

packages/fuselage/src/styleTokens.js

The overly complicated regular expression was missing multiples of 100.

fix: Loosen x-measures parsing

---

packages/emitter/README.md

chore: Correct badges in @rocket.chat/emitter README

---

packages/icons/.eslintrc
packages/icons/.eslintrc.js
packages/icons/.prettierignore
packages/icons/.prettierrc
packages/icons/package.json
packages/icons/scripts/build.js
packages/icons/scripts/files.js
packages/icons/scripts/font.js
packages/icons/scripts/glyphs.js
packages/icons/scripts/icons.js
packages/icons/scripts/log.js
packages/icons/scripts/svg.js

Script(s) changed to verify: 
- `"prettier-format": "prettier --config .prettierrc 'scripts/**/*.js' --write",`

feat: Prettier installation for icons

---

packages/fuselage/fuselage.d.ts
packages/fuselage/package.json

Moves from Rocket.Chat repo to the package itself.

feat: Fuselage typings

---

packages/fuselage-polyfills/index.js
packages/fuselage-polyfills/package.json
yarn.lock

This new polyfill should fix some IE issues:
**Quote Issue:**
**File Attached Issue:**

feat: new Event() polyfill

---

packages/fuselage/fuselage.d.ts

fix: Add more type definitions

---

packages/fuselage/fuselage.d.ts

There is no `HTMLSectionElement` declared in `@types/react`. Preferable to use `HTMLElement`.

fix: Remove reference to inexistent interface

---

packages/fuselage/fuselage.d.ts

It adds `circleCount` and `disabled` props to `Throbber` type definition.

fix: Add more props to Throbber type definition

---

packages/fuselage/src/components/Box/AnimatedVisibility/index.js
packages/fuselage/src/components/Box/BoxTransforms.ts
packages/fuselage/src/components/Box/Flex/index.js
packages/fuselage/src/components/Box/Scrollable/index.js
packages/fuselage/src/components/Box/index.js
packages/fuselage/src/components/Margins/index.js
yarn.lock

React 17 warns against `undefined` as context value because it assumes it was not properly set. This PR changes it to `null`.

fix: Prefer null over undefined on BoxTransforms

---

packages/fuselage/fuselage.d.ts

fix: Pagination and Select prop types

---

packages/fuselage/fuselage.d.ts

fix: Typings for ProgressBar

---

packages/fuselage/fuselage.d.ts

chore: Export prop types Fuselage

---

.github/workflows/cd.yml

This should avoid an additional build step before publishing to NPM.

Store build on CI

---

packages/message-parser/src/definitions.ts
packages/message-parser/src/index.ts

fix: message-parser Unordered List definition

---

packages/fuselage/src/components/SelectPaginated/PaginatedMultiSelect.js

fix(fuselage): fix duplicated values on paginated multi select

---

packages/peggy-loader/src/index.ts
yarn.lock

The option `format: 'commonjs'` must be default, otherwise Peggy.js will output an IIFE.

fix: Peggy loader options

---

packages/fuselage/src/components/Box/Position/Position.d.ts
packages/fuselage/src/components/Box/Position/Position.js
packages/fuselage/src/components/Box/Position/PositionAnimated.d.ts
packages/fuselage/src/components/Box/Position/PositionAnimated.js
packages/fuselage/src/components/Box/Position/index.ts

Splits `Position` and `PositionAnimated` modules and attaches `*.d.ts` files of them.

refactor(types): Type definitions for Position and PositionAnimated

---

packages/fuselage/src/components/RadioButton/index.d.ts

fix: Typings for RadioButton

---

packages/fuselage/src/components/Box/index.d.ts

fix: Typings for Position and PositionAnimated properly exported

---

packages/fuselage/src/components/Box/Position/PositionAnimated.d.ts

fix: PositionAnimated exported type

---

packages/fuselage/src/components/Box/Position/PositionAnimated.d.ts
packages/fuselage/src/components/Tile/Tile.tsx

fix: Export correctly props and types from PositionAnimated and Tile components

---

packages/string-helpers/package.json

fix(string-helpers):  typesVersions

---

packages/eslint-config-alt/typescript/index.js
packages/fuselage/src/components/Message/Metrics/index.tsx
packages/message-parser/src/utils.ts

It needs a special rule for TypeScript.

fix(eslint): Add missing ESLint rule for TypeScript

---

packages/ui-kit/src/index.ts
packages/ui-kit/src/rendering/surfaces/UiKitParserAttachment.spec.ts
packages/ui-kit/src/rendering/surfaces/UiKitParserAttachment.ts
packages/ui-kit/src/rendering/surfaces/uiKitAttachment.ts

feat(ui-kit): Attachment Surface

---

packages/fuselage/src/components/Select/index.d.ts

fix: Export MultiSelect component in .d.ts file

---

packages/fuselage/src/components/Menu/index.d.ts

fix: Menu component and options.label prop type

---

packages/fuselage/src/components/Table/index.d.ts

Add the props `striped`, `sticky`, and `fixed` into `Table` component.

fix: Table props

---

packages/fuselage/src/components/EmailInput/index.d.ts

chore: Missing EmailInput type

---

packages/fuselage/src/components/SelectPaginated/PaginatedSelect.js

The PaginatedSelect was missing the prevent default property, causing the options to close whenever someone clicked the scroll bar.

fix(fuselage): No preventDefault on PaginatedSelect

---

packages/fuselage/src/components/Tabs/index.d.ts

fix: Missing Tab definitions

---

packages/fuselage/src/components/Tabs/index.d.ts

fix: Add Tab.Item definition

---

packages/fuselage/src/components/Sidebar/index.d.ts

fix: Missing Sidebar type

---

packages/fuselage/src/components/Sidebar/TopBar.stories.mdx
packages/fuselage/src/components/Sidebar/index.d.ts

chore(fuselage): Nested sidebar props type

---

packages/onboarding-ui/src/index.ts

fix(onboarding-ui): Export RequestTrialPage

---

packages/onboarding-ui/src/index.ts

chore(onboarding-ui): Missing export page components

---

packages/onboarding-ui/src/forms/RequestTrialForm/RequestTrialForm.tsx

fix(onboarding-ui): Missing default values

---

packages/fuselage-hooks/src/useResizeObserver.ts

fix(fuselage-hooks): useResizeObserver Ref type

---

packages/fuselage/src/components/Sidebar/index.d.ts

fix(fuselage): Add/Update Sidebar.TopBar Action, Toolbox, Section types

---

packages/message-parser/src/definitions.ts
packages/message-parser/src/grammar.pegjs
packages/message-parser/src/utils.ts
packages/message-parser/tests/codeFence.test.ts
packages/message-parser/tests/emphasis.test.ts
packages/message-parser/tests/escaped.test.ts
packages/message-parser/tests/image.test.ts
packages/message-parser/tests/link.test.ts
packages/message-parser/tests/strikethrough.test.ts
packages/message-parser/tests/strongEmphasis.test.ts
packages/message-parser/tests/url.test.ts

_[A brand new Gist](https://gist.github.com/24dddfa97bef58f46ac2ce0f80c58ba4)_
closes #455
and should close https://github.com/RocketChat/Rocket.Chat/issues/8989
closes https://github.com/RocketChat/Rocket.Chat/issues/21184
closes https://github.com/RocketChat/Rocket.Chat/issues/7707
closes https://github.com/RocketChat/Rocket.Chat/issues/21184
closes https://github.com/RocketChat/Rocket.Chat/issues/5218

fix(message-parser): Fix Url and Escaped Markdown

---

packages/fuselage/src/components/Sidebar/Item.tsx

chore(fuselage): Missing sidebar item icon prop

---

packages/fuselage-hooks/src/usePosition.ts

fix(fuselage-hooks): usePosition fallback

---

packages/fuselage/src/components/Message/index.tsx

chore: Message subcomponents export

---

packages/fuselage-ui-kit/src/contexts/kitContext.ts
packages/fuselage-ui-kit/src/hooks/useUiKitState.ts
packages/fuselage-ui-kit/src/surfaces/FuselageSurfaceRenderer.tsx

chore: Review #600

---

packages/fuselage-hooks/src/useBorderBoxSize.ts
packages/fuselage-hooks/src/useContentBoxSize.ts

fix(fuselage-hooks): Handle ResizeObserver bug on Firefox ESR 91

---

package.json

chore: Docs task

---

.github/workflows/cd.yml
.github/workflows/ci-pr.yml

chore: Turbo Repo cache

---

.github/PULL_REQUEST_TEMPLATE.md

docs(monorepo): Update pull request template

---

packages/onboarding-ui/src/forms/RegisteredServerForm/RegisteredServerForm.stories.tsx
packages/onboarding-ui/src/forms/RegisteredServerForm/RegisteredServerForm.tsx
packages/onboarding-ui/src/pages/RegisteredServerPage/RegisteredServerPage.stories.tsx
packages/onboarding-ui/src/pages/RegisteredServerPage/RegisteredServerPage.tsx

It fixes `policyHref` prop's default value to the correct URL.

chore(onboarding-ui): RegisteredServerPage privacy url

---

packages/fuselage/src/components/Field/Field.stories.tsx

- Add more information about how to use Field components
https://www.loom.com/share/b55dd1bfec874ebfa3aa67f4a0fe8849

docs(fuselage): Add Field use examples

---

packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/pages/SomethingWentWrongPage/SomethingWentWrongPage.stories.tsx
packages/onboarding-ui/src/pages/SomethingWentWrongPage/SomethingWentWrongPage.tsx

- Added requestId prop to SomethingWentWrongPage to make easier for the contact support look up the logs and find out what went wrong.

improve(onboarding-ui): Add requestId prop into SomethingWentWrongPage

---

packages/fuselage/src/components/States/States.styles.scss

chore(fuselage): Update subtitle and icon margin in States Component

---

packages/fuselage/src/components/InputBox/styles.scss

fix(fuselage): InputBox style

---

packages/fuselage/src/components/MultiSelect/MultiSelect.d.ts
packages/fuselage/src/components/MultiSelect/MultiSelect.js
packages/fuselage/src/components/MultiSelect/MultiSelect.stories.tsx
packages/fuselage/src/components/Options/Options.stories.tsx
packages/fuselage/src/components/Options/Options.tsx
packages/fuselage/src/components/Select/Select.stories.tsx
packages/fuselage/src/components/Select/Select.tsx
packages/fuselage/src/components/Select/SelectFiltered.tsx

Fixes #441
Add emptyPlaceholder to Options, Select and MultiSelect components. 
Update Select and Options stories with usage example.

improve(fuselage): Add customEmpty to Options

---

packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx
packages/onboarding-ui/src/pages/OrganizationInfoPage/OrganizationInfoPage.stories.tsx
packages/onboarding-ui/src/pages/OrganizationInfoPage/OrganizationInfoPage.tsx

improve(onboarding-ui): Render back button conditionally

---

.github/PULL_REQUEST_TEMPLATE.md
.github/pr-title-checker-config.json

docs(monorepo): fix PR template to match pr-title-checker

---

packages/fuselage/package.json
packages/fuselage/src/components/MultiSelect/MultiSelect.js
packages/fuselage/src/helpers/isForwardRefType.ts
yarn.lock

It fixes issues reported by @dougfabris.

fix(fuselage,regression): `MultiSelect` errors

---

packages/fuselage/.storybook/helpers.js
packages/fuselage/src/components/Menu/Menu.stories.tsx
packages/fuselage/src/components/Menu/Menu.tsx
packages/fuselage/src/components/Options/Options.stories.tsx
packages/fuselage/src/components/Options/Options.tsx
packages/fuselage/src/components/Options/styles.scss
packages/fuselage/src/components/Options/useCursor.ts

feat(fuselage): Extend menu options props

---

package.json
packages/eslint-config-alt/typescript/index.js
packages/fuselage-ui-kit/src/blocks/ImageBlock.styles.tsx
packages/fuselage-ui-kit/src/elements/ImageElement.styles.tsx
packages/fuselage/src/components/Button/Button.tsx
packages/fuselage/src/components/Message/MessageBlock.tsx
packages/fuselage/src/components/MultiSelect/MultiSelectFiltered.tsx
packages/fuselage/src/components/MultiSelect/MultiSelectFilteredAnchor.tsx
packages/fuselage/src/components/Position/Position.tsx
packages/fuselage/src/components/PositionAnimated/PositionAnimated.tsx
packages/fuselage/src/components/Select/SelectFiltered.tsx
packages/fuselage/src/components/SelectPaginated/PaginatedMultiSelect.tsx
packages/fuselage/src/components/SelectPaginated/PaginatedSelect.tsx
packages/fuselage/src/components/SelectPaginated/PaginatedSelectFiltered.tsx
packages/fuselage/src/components/Sidebar/Item.tsx
packages/logo/src/TaggedRocketChatLogo/TaggedRocketChatLogo.styles.tsx
packages/onboarding-ui/src/common/BackgroundLayer.styles.tsx
packages/onboarding-ui/src/common/FormPageLayout.styles.tsx
packages/onboarding-ui/src/common/List/List.styles.tsx
packages/styled/src/styled.spec.ts
turbo.json

fix(fuselage, regression): MultiSelectFiltered

---

packages/fuselage/src/components/Select/Select.tsx
packages/fuselage/src/components/Select/SelectAnchorParams.ts
packages/fuselage/src/components/Select/SelectFiltered.tsx
packages/fuselage/src/components/Select/SelectFilteredAnchor.tsx

Fix Select filter. Refactor Select anchor.

fix(fuselage, regression): Select filter and anchor overhaul

---

packages/fuselage/src/components/Select/Select.tsx

Add onClick to handle selected option.

fix(fuselage, regression): listen for clicks on `Select` options

---

packages/onboarding-ui/src/pages/InformationPage/InformationPage.spec.tsx
packages/onboarding-ui/src/pages/InformationPage/InformationPage.stories.tsx
packages/onboarding-ui/src/pages/InformationPage/InformationPage.tsx
packages/onboarding-ui/src/pages/InformationPage/index.ts

Added a reusable Information page that can replace pages with the same format and avoid creating new ones that only the strings differ from each other.

feat(onboarding-ui): create reusable InformationPage

---

packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/pages/RedirectPage/RedirectPage.spec.tsx
packages/onboarding-ui/src/pages/RedirectPage/RedirectPage.stories.tsx
packages/onboarding-ui/src/pages/RedirectPage/RedirectPage.tsx
packages/onboarding-ui/src/pages/RedirectPage/index.ts

Adding a redirect page with a countdown.
https://app.clickup.com/t/238ku3u

feat(onboarding-ui): create redirect page

---

packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.spec.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.stories.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/index.ts
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.spec.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.stories.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/TitleCreateFirstMemberPage.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/index.ts

- Add CreateWorkspacePage;
https://app.clickup.com/t/238ku3u

feat(onboarding-ui): add CreateFirstWorkspacePage

---

packages/onboarding-ui/src/pages/OrganizationInfoPage/OrganizationInfoPage.tsx

- Added optional subtitle prop to OrganizationInfoPage;
- Updated description type from string to ReactNode;
##Task Link
https://app.clickup.com/t/238ku3u

feat(onboarding-ui): add optional subtitle prop to OrganizationInfoPage

---

packages/fuselage/src/components/Message/Message.tsx
packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/styles/colors.scss

chore: Selected messages style

---

packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.spec.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.stories.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.spec.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.stories.tsx
packages/onboarding-ui/src/pages/CreateFirstMemberPage/CreateFirstMemberPage.tsx

- Update Form props types;
- Refactor page;
- Update related storybook

feat: update CreateFirstMemberPage props

---

packages/onboarding-ui/README.md
packages/onboarding-ui/package.json
yarn.lock

chore(onboarding-ui): Set react-i18nex as peerDependencies

---

packages/fuselage/src/components/Message/MessageSystem/MessageSystem.stories.tsx
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.tsx

fix(fuselage): Missing type on system message

---

packages/onboarding-ui/src/index.ts

feat(onboarding-ui): export BackgroundLayer

---

tools/bump/bump-next.mjs

chore(tools): bump-next fallback

---

packages/onboarding-ui/src/pages/AwaitingConfirmationPage/AwaitingConfirmationPage.tsx
packages/onboarding-ui/src/pages/CheckYourEmailPage/CheckYourEmailPage.tsx
packages/onboarding-ui/src/pages/ConfirmationProcessPage/ConfirmationProcessPage.tsx
packages/onboarding-ui/src/pages/EmailConfirmedPage/EmailConfirmedPage.tsx
packages/onboarding-ui/src/pages/InformationPage/InformationPage.tsx
packages/onboarding-ui/src/pages/InvalidLinkPage/InvalidLinkPage.tsx
packages/onboarding-ui/src/pages/LoginLinkEmailPage/LoginLinkEmailPage.tsx
packages/onboarding-ui/src/pages/ResetPasswordConfirmationPage/ResetPasswordConfirmationPage.tsx
packages/onboarding-ui/src/pages/SomethingWentWrongPage/SomethingWentWrongPage.tsx

Refactor box properties to specific fontScale

refactor(onboarding-ui): change box properties to specific fontScale

---

packages/fuselage-toastbar/src/ToastBarTimed.tsx
packages/fuselage/src/components/ToastBar/ToastBar.tsx
packages/fuselage/src/components/ToastBar/styles.scss

fix(fuselage-toastbar): ToastBar close function

---

packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.styles.scss
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.tsx

fix(fuselage): Wrong className in ThreadMessage component

---

packages/fuselage/src/components/ToastBar/ToastBar.tsx
packages/fuselage/src/components/ToastBar/styles.scss

fix(fuselage): ToastBar style

---

packages/fuselage/src/components/Message/Messages.styles.scss

fix(fuselage): List style affecting other components

---

packages/fuselage/src/components/Message/Messages.styles.scss

Fix sequential message padding
Wrong padding spacing in sequential messages
I opened a [PR to Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/pull/25631) to include sequential param to Message Component

fix(fuselage): Adjusting sequential messages padding

---

packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/mixins.scss

fix(fuselage): Message negative margins

---

packages/fuselage-ui-kit/README.md
packages/fuselage-ui-kit/package.json
yarn.lock

chore(fuselage-ui-kit): Fix peer dep

---

packages/fuselage-hooks/README.md
packages/fuselage-hooks/package.json
packages/fuselage-hooks/src/useMediaQueries.ts
yarn.lock

Replaces `useSubscription` usage with a shim of `useSyncExternalStore`.
Check notes at https://reactjs.org/docs/hooks-reference.html#usesyncexternalstore.

refactor(fuselage-hooks): Prepare for React 18's `useSyncExternalStore`

---

packages/fuselage/src/styles/colors.scss

fix(fuselage): Surface values using  css var

---

packages/fuselage/src/styles/variables/button-colors.scss

fix: Button disabled color

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/emoji.test.ts

fix(message-parser): Expand emoji detection

---

yarn.lock

chore(monorepo): update depencencies

---

packages/fuselage-toastbar/README.md
packages/fuselage-toastbar/package.json
packages/fuselage-ui-kit/package.json
packages/onboarding-ui/README.md
packages/onboarding-ui/package.json
yarn.lock

chore(monorepo): move peer deps

---

packages/fuselage/src/components/Button/IconButton.tsx

fix(fuselage): Add default type prop to button

---

packages/fuselage/src/components/ButtonGroup/ButtonGroup.stories.tsx

chore(fuselage): improve button group stories

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/emoji.test.ts

fix(message-parser): Emoji skin tone detection

---

packages/fuselage/src/components/Button/Button.tsx
packages/fuselage/src/components/Button/IconButton.tsx
packages/fuselage/src/components/Message/MessageRole.tsx
packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.tsx
packages/fuselage/src/components/Tag/styles.scss

fix(fuselage): Tag Component states

---

packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusIndicator.stories.tsx
packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusIndicator.styles.scss
packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusIndicatorText.tsx
packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusPrivateIndicator.tsx

Add a component to show the text status in a message.
This component will be used to show the translation provider on rocketchat app

feat(fuselage): Add message status indicator text component

---

packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusPrivateIndicator.tsx

fix(fuselage): props for `MessageStatusPrivateIndicator`

---

packages/fuselage/src/components/Message/MessageStatusIndicator/index.ts

Wass missing the component export

fix(fuselage): Export message status text component

---

packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss

fix: Adjusting MessageSystem font-size

---

packages/fuselage-ui-kit/src/hooks/useUiKitState.ts

This PR is a fix on the dispatch action, which was not working when the context is different from FORMS causing the behavior of unfocusing every time an input is sent
For further information about this functionality, please reach [this PR](https://github.com/RocketChat/fuselage/pull/747)

fix: fix on dispatch action

---

packages/fuselage-hooks/src/usePosition.spec.ts
packages/fuselage-hooks/src/usePosition.ts
packages/fuselage/src/components/Menu/Menu.spec.tsx

feat(fuselage-hooks): `usePosition` listening to components size changes

---

packages/fuselage/src/components/MultiSelect/MultiSelect.tsx

fix(fuselage): Multiselect show

---

packages/fuselage/src/components/Button/IconButton.stories.tsx

Update IconButton stories with sizes and variants

chore(fuselage): update IconButton stories 

---

packages/fuselage/src/components/Message/MessageRole.tsx
packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss

fix(fuselage): Message roles size

---

packages/fuselage/src/components/Avatar/Avatar.tsx
packages/fuselage/src/components/Avatar/styles.scss
packages/fuselage/src/styles/lengths.scss

chore(fuselage): improve Avatar border-radius

---

packages/fuselage/src/components/Sidebar/styles.scss

Fix alignment of avatar sidebar when the image is smaller than the text.
Before:
After:

fix(fuselage): misaligned sidebar image

---

packages/message-parser/src/utils.ts
packages/message-parser/tests/link.test.ts
packages/message-parser/tests/url.test.ts

fix(message-parser): Fix payload generation for custom protocols

---

.kodiak.toml

chore: Kodiak

---

packages/layout/.storybook/preview.tsx
packages/layout/src/DarkModeProvider.tsx

chore: Small change on Layout package @next

---

packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

secondary-info -> annotation
and created title color variable

fix(fuselage): Sidebar colors

---

packages/fuselage/package.json
packages/fuselage/src/components/CodeSnippet/CodeSnippet.spec.tsx
packages/fuselage/src/components/CodeSnippet/CodeSnippet.stories.tsx
packages/fuselage/src/components/CodeSnippet/CodeSnippet.tsx
packages/layout/README.md

- Add extra CodeSnippet CustomButtonName story;
- Add extra test cases in test file
Documentation I followed
https://storybook.js.org/addons/@storybook/testing-react

chore(fuselage): Update CodeSnippet unit tests

---

packages/fuselage/src/components/Option/Option.styles.scss

chore(fuselage): OptionTitle fontScale

---

packages/ui-kit/src/blocks/LayoutBlock.ts
packages/ui-kit/src/blocks/LayoutBlockType.ts
packages/ui-kit/src/blocks/layout/VideoConferenceBlock.ts
packages/ui-kit/src/rendering/surfaces/UiKitParserMessage.ts

feat(ui-kit): video_conf block

---

packages/onboarding-ui/src/forms/CreateCloudWorkspaceForm/CreateCloudWorkspaceForm.tsx
packages/onboarding-ui/src/forms/NewAccountForm/NewAccountForm.tsx

Fix the link on the New Account Form that was going to a broken url and fix typo.
[https://rocketchat.atlassian.net/jira/software/c/projects/CS/boards/27?modal=detail&selectedIssue=CS-61&assignee=62b4acd6cebad33432f87c5b](https://rocketchat.atlassian.net/jira/software/c/projects/CS/boards/27?modal=detail&selectedIssue=CS-61&assignee=62b4acd6cebad33432f87c5b)

fix: Privacy policy broken link on New Account Form

---

packages/fuselage/src/components/Box/props.stories.mdx
packages/fuselage/src/styleTokens.ts

chore(fuselage): Surfaces variation to box prop

---

packages/fuselage/src/components/ToastBar/ToastBar.tsx

chore(fuselage): Add aria-role alert to toastbar

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/mention.test.ts

Due to Matrix Protocol integration, the username follows the pattern:
`@user:server.com` 
The user mention rule was changed in `grammar.pegjs` file and added some tests

feat(message-parser): Add Matrix Protocol username pattern to User Mention

---

packages/message-parser/src/utils.ts
packages/message-parser/tests/emoji.test.ts
packages/message-parser/tests/emoticons.test.ts

TC-98
TC-101
Preserve the colon character when the emoji is surrounded by plain text.

fix(message-parser): removes colons from timestamps

---

yarn.lock

chore(monorepo): security packages upgrade

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/emoticons.test.ts

TC-114
The input  `D:` was resulting in the wrong output: `:fearfulc:`
The change makes the correction to `:fearful:`
closes https://github.com/RocketChat/Rocket.Chat/issues/26942

fix(message-parser): Update emoticon to output :fearful: emoji

---

packages/fuselage/src/components/Callout/Callout.stories.tsx
packages/fuselage/src/components/Callout/Callout.styles.scss

fix(fuselage): Callout Component Style Update

---

packages/fuselage/src/styleTokens.ts
packages/layout/.storybook/main.ts
packages/layout/src/BackgroundLayer/BackgroundLayer.stories.tsx
packages/layout/src/BackgroundLayer/BackgroundLayer.styles.tsx
packages/layout/src/FormPageLayout/FormPageLayout.styles.tsx
packages/layout/src/HorizontalWizardLayout/HorizontalWizardLayout.stories.tsx
packages/layout/src/HorizontalWizardLayout/HorizontalWizardLayout.tsx
packages/layout/src/Link.tsx
packages/layout/src/VerticalWizardLayout/VerticalWizardLayout.stories.tsx
packages/layout/src/index.ts
packages/onboarding-ui/src/forms/LoginForm/LoginForm.tsx
packages/onboarding-ui/src/pages/LoginPage/LoginPage.tsx

fix(layout): Design adjustments

---

packages/fuselage/src/styles/colors.scss

chore(fuselage): Add "color" prefix to css vars 

---

packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.styles.scss
packages/fuselage/src/components/Tag/Tag.tsx

fix(fuselage): Tag not receiving props properly

---

packages/fuselage/src/components/ToastBar/ToastBar.stories.tsx
packages/fuselage/src/components/ToastBar/ToastBar.tsx

chore(fuselage): Add elevation to ToastBar Component

---

packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/styleTokens.ts
packages/fuselage/src/styles/colors.scss

chore: Add Background scss function

---

packages/fuselage/src/Theme.ts
packages/fuselage/src/components/Box/stylingProps.ts
packages/fuselage/src/index.ts
packages/fuselage/src/styleTokens.ts

chore: Create Theme and Palete objects

---

packages/fuselage/src/components/Message/MessageGenericPreview/MessageGenericPreview.styles.scss
packages/fuselage/src/components/Option/Option.styles.scss
packages/fuselage/src/components/Table/Table.styles.scss
packages/fuselage/src/components/Table/TableSelection.tsx
packages/fuselage/src/styles/colors.scss
packages/fuselage/src/styles/variables/input-colors.scss

chore(fuselage): Table and options using color palette 

---

packages/fuselage/src/components/Accordion/Accordion.styles.scss
packages/fuselage/src/components/Badge/Badge.stories.tsx
packages/fuselage/src/components/Badge/Badge.styles.scss
packages/fuselage/src/components/Callout/Callout.styles.scss
packages/fuselage/src/components/CodeSnippet/CodeSnippet.styles.scss
packages/fuselage/src/components/Modal/Modal.styles.scss
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Throbber/Throbber.styles.scss
packages/fuselage/src/styles/colors.scss

chore(fuselage): Update tokens

---

packages/icons/README.md
yarn.lock

chore(monorepo): update packages for security

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/url.test.ts

chore(message-parser): Accept urls starting with numbers

---

packages/fuselage/src/Theme.ts
packages/fuselage/src/components/Message/MessageDivider/MessageDivider.styles.scss
packages/fuselage/src/components/Message/MessageToolbox/MessageToolbox.styles.scss
packages/fuselage/src/styleTokens.ts
packages/fuselage/src/styles/colors.scss

chore(fuselage): Remove background token

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/mention.test.ts

Enable the possibility to handle user mentions with `@` characters and highlight them
After writing `@username@example.com` in the message box it's given:
With and without Real Name display:
https://github.com/RocketChat/Rocket.Chat/issues/26869
TC-254

fix(message-parser): User mention with @ character

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/escaped.test.ts

Previously the escape character `\` was escaping everything. 
To avoid unexpected text formatting errors it was restricted to only escape curtains chars like: * _ ~ ` # .
https://github.com/RocketChat/Rocket.Chat/issues/26907
https://github.com/RocketChat/Rocket.Chat/issues/26800
The Shrug issue will be fixed after this Pull Request and https://github.com/RocketChat/Rocket.Chat/pull/27233 are released
TC-99

fix(message-parser): Escaping only necessary characters 

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/link.test.ts

Add rule to accept file path structure in Reference URL markdown
The URL markdown should accept the file path pattern.
e.g: 
```
[File Path](C:/Users/user1/Documents/projects/file.js)
[notes link](notes://Server/C3257116002CAD60/0/CCAF6BE2824A1F49432588D2001FA73E)
```
The example above should render a link
**Output:** 
**Previous output:**
https://github.com/RocketChat/Rocket.Chat/issues/27065 
TC-255

fix(message-parser): Add file path structure to URL reference markdown

---

packages/fuselage/src/components/Message/MessageDivider/MessageDivider.styles.scss
packages/fuselage/src/components/Message/MessageGenericPreview/MessageGenericPreview.styles.scss

Fix message generic preview hover background-color. 
Fix MessageDivider spacing.

fix(fuselage): Message palette colors

---

packages/fuselage/src/components/Banner/Banner.stories.js
packages/fuselage/src/components/Banner/Banner.styles.scss
packages/fuselage/src/components/Banner/Banner.tsx

feat(fuselage): Update Banner Component style

---

packages/fuselage-hooks/src/useStorage.ts

it works fine cross pages, but at the same page it doesnt trigger the event =/

fix(fuselage-hooks): fix storage not reacting if there are multiple in same page

---

packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.styles.scss

Add cursor pointer to thread message preview row

chore: add cursor pointer to thread message preview row

---

packages/fuselage/src/components/Tile/Tile.styles.scss

chore: Add border on tile elevation

---

packages/fuselage/src/components/Sidebar/Item.stories.tsx
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/styles/colors.scss

chore(fuselage): Allow scape colors tokens

---

packages/fuselage-toastbar/src/ToastBarZone.tsx
packages/fuselage/src/components/Banner/Banner.styles.scss

chore(fuselage): z-index sanitization on Banner and ToastBar

---

packages/fuselage/src/styles/mixins/elevation.scss

fix(fuselage): Elevation token

---

packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.styles.scss
packages/fuselage/src/components/Tag/Tag.tsx
packages/fuselage/src/styles/colors.scss

It also fixes the ellipsis issue

feat(fuselage): Featured Tag variant

---

packages/fuselage-toastbar/src/ToastBarZone.tsx
packages/fuselage/src/components/Box/props.stories.mdx
packages/fuselage/src/components/Box/stylingProps.ts
packages/fuselage/src/components/ToastBar/ToastBar.tsx
packages/fuselage/src/styles/mixins/elevation.scss

chore(fuselage-toastbar): Toastbar Elevation

---

packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.styles.scss
packages/fuselage/src/components/Tag/Tag.tsx
packages/fuselage/src/styles/colors.scss

Reverts RocketChat/fuselage#922

fix: Revert "feat(fuselage): Featured Tag variant"

---

packages/fuselage/src/components/Banner/Banner.styles.scss

fix(fuselage): Revert Banner Elevation

---

packages/fuselage-toastbar/src/ToastBarZone.tsx
packages/fuselage/src/components/Banner/Banner.styles.scss
packages/fuselage/src/components/ToastBar/ToastBar.tsx

chore(fuselage): Banner & Toastbar visual tweaks

---

packages/fuselage/src/Theme.ts
packages/fuselage/src/styles/colors.scss

Update token system:
- remove status-background-service-3
- remove status-font-service-3
- add surface-featured
- add surface-featured-hover

chore(fuselage): Surface featured

---

packages/fuselage/src/components/Pagination/Pagination.tsx

Whatever, let the use set the number per page, no magic is required, if they have less items its fine ...

fix(fuselage): Pagination number

---

packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.styles.scss
packages/fuselage/src/components/Tag/Tag.tsx

feat(fuselage): Tag Featured Variant

---

packages/fuselage-hooks/src/usePosition.spec.ts
packages/fuselage/src/components/MultiSelect/MultiSelect.tsx
packages/fuselage/src/components/Option/Option.spec.tsx
packages/fuselage/src/components/Option/Option.stories.tsx
packages/fuselage/src/components/Option/Option.styles.scss
packages/fuselage/src/components/Option/Option.tsx
packages/fuselage/src/components/Options/Options.tsx
packages/fuselage/src/components/OptionsPaginated/OptionsPaginated.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelect.tsx
packages/fuselage/src/helpers/prevent.ts

Add disabled variant to `Option` component, also move `prevent` to a helper function since it was repeating too much.

feat(fuselage): add disabled variant to option

---

packages/fuselage/src/components/Option/Option.tsx

Add `aria-disabled` prop to Option component

feat(fuselage): add aria-disabled prop to Option component

---

packages/fuselage/src/components/Accordion/Accordion.styles.scss
packages/fuselage/src/components/Divider/Divider.styles.scss
packages/fuselage/src/components/InputBox/InputBox.styles.scss
packages/fuselage/src/components/Tabs/Tabs.styles.scss
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.styles.scss
packages/fuselage/src/styles/lengths.scss
packages/fuselage/src/styles/mixins/shadows.scss

chore(fuselage): Small fix on shadow focus border

---

packages/fuselage/src/styleTokens.ts

fix(fuselage): Badge bg token colors

---

packages/fuselage/src/components/ButtonGroup/ButtonGroup.stories.tsx
packages/fuselage/src/components/ButtonGroup/ButtonGroup.styles.scss
packages/fuselage/src/components/ButtonGroup/ButtonGroup.tsx
packages/fuselage/src/components/Divider/Divider.stories.tsx
packages/fuselage/src/components/Modal/ModalFooterControllers.tsx
packages/fuselage/src/components/Sidebar/SidebarActions.tsx

chore(fuselage): Replace medium prop as default size of ButtonGroup

---

packages/fuselage/src/components/Modal/Modal.tsx
packages/fuselage/webpack.config.js

chore(fuselage): Remove FocusScope from Modal

---

packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

Change sidebar backgroundColor to surface-neutral
[DSA-31](https://rocketchat.atlassian.net/browse/DSA-31)
[DSA-31]: https://rocketchat.atlassian.net/browse/DSA-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): Change sidebar backgroundColor

---

packages/fuselage/package.json
yarn.lock

chore(fuselage): Update react-virtuoso dep version

---

packages/fuselage/package.json
yarn.lock

chore(fuselage): Revert `react-virtuoso` version

---

packages/fuselage/src/components/Option/OptionSkeleton.tsx

chore(fuselage): `OptionSkeleton` Visual Changes

---

packages/fuselage-hooks/src/usePosition.ts

fix(fuselage-hooks): Fix `usePosition`

---

packages/fuselage/src/styles/variables/buttons.scss

chore(fuselage): Apply status-font on icon colors

---

packages/fuselage/src/components/Sidebar/Sidebar.stories.tsx
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Sidebar/SidebarBanner.tsx
packages/fuselage/src/components/Sidebar/index.tsx

feat(fuselage): SidebarBanner component

---

packages/fuselage/src/components/Option/Option.tsx

chore(fuselage): Add AllHTMLAtributes to OptionProps type

---

packages/fuselage-ui-kit/src/elements/OverflowElement.tsx
packages/fuselage/src/components/Menu/Menu.stories.tsx
packages/fuselage/src/components/Menu/Menu.tsx
packages/fuselage/src/components/Options/Options.tsx
packages/fuselage/src/components/Options/useCursor.ts

chore(fuselage): Add disabled prop for options in `Menu` component

---

packages/fuselage/src/components/Sidebar/SidebarActions.tsx

chore(fuselage): Adjust SidebarActions style

---

packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

fix(fuselage): Fix scrolling issues due menu button wrapper

---

packages/fuselage/src/components/InputBox/InputBox.styles.scss

[OC-687](https://rocketchat.atlassian.net/browse/OC-687)
[OC-687]: https://rocketchat.atlassian.net/browse/OC-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): Fix InputBox type date color

---

packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

[ARCH-155](https://rocketchat.atlassian.net/browse/ARCH-155)
Also solves the chat list "over scrolling" after the end of the list
[ARCH-151](https://rocketchat.atlassian.net/browse/ARCH-151)
[ARCH-155]: https://rocketchat.atlassian.net/browse/ARCH-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ARCH-151]: https://rocketchat.atlassian.net/browse/ARCH-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): SidebarItem menu glitch on hover

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/src/utils.ts
packages/message-parser/tests/email.test.ts
packages/message-parser/tests/link.test.ts
packages/message-parser/tests/strikethrough.test.ts
packages/message-parser/tests/url.test.ts

A stricter `link()` helper will help to avoid false positives in unit tests.

fix(message-parser): Differ `link`, `autoLink`, and `autoEmail` helpers

---

packages/fuselage/src/components/OptionsPaginated/OptionsPaginated.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelect.tsx
packages/fuselage/src/components/PaginatedSelect/index.ts

fix(fuselage): Adjusted PaginatedMultiSelect to keep received/returned values consistent

---

packages/fuselage/src/components/Message/Messages.styles.scss

Fix selected-messages color contrast while selecting messages to export.

fix(fuselage): selected-messages color

---

packages/fuselage/src/components/Skeleton/Skeleton.stories.tsx
packages/fuselage/src/components/Skeleton/Skeleton.styles.scss
packages/fuselage/src/components/Skeleton/Skeleton.tsx

feat(fuselage): Skeleton Circle Variant

---

packages/onboarding-ui/src/pages/OauthAuthorizationPage/OauthAuthorizationPage.tsx

chore(onboarding-ui): improve `OauthAuthorizationPage` when clientName is undefined

---

packages/fuselage/src/components/AutoComplete/AutoComplete.stories.tsx
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx

- refactor AutoComplete to show initial values, when given
- improve AutoComplete stories
- remove unused props
- add `multiple` flag to handle with multiple values selected internally
- refactor renderSelected usage

refactor(fuselage): AutoComplete 

---

packages/fuselage/src/components/Avatar/Avatar.styles.scss

fix(fuselage): Avatar element excending container width

---

packages/message-parser/src/grammar.pegjs
packages/message-parser/tests/inlineCode.test.ts

The Back-stick char  ` was being considered to be part of the local-part of an email address. 
**Previous:**
**Current (NOW):**

fix(message-parser): Inline Code with mention and/or mail pattern

---

packages/fuselage/src/components/Button/Button.styles.scss

[DSA-116](https://rocketchat.atlassian.net/browse/DSA-116)
button `min width` must be double of its height:
prev: 
change:
[DSA-116]: https://rocketchat.atlassian.net/browse/DSA-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): button min-width

---

packages/fuselage/src/components/Button/IconButton.stories.tsx
packages/fuselage/src/components/Button/IconButton.tsx

chore(fuselage): add option to use `IconButton` with emoji

---

packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/IconButton.stories.tsx
packages/fuselage/src/components/Button/IconButton.tsx
packages/fuselage/src/styles/mixins/states.scss
packages/fuselage/src/styles/primitives/button.scss
packages/fuselage/src/styles/variables/buttons.scss

[DSAR-123](https://rocketchat.atlassian.net/browse/DSAR-123)
[DSAR-123]: https://rocketchat.atlassian.net/browse/DSAR-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): `IconButton` variants

---

packages/fuselage/src/components/ToastBar/ToastBar.stories.tsx
packages/fuselage/src/components/ToastBar/ToastBar.styles.scss
packages/fuselage/src/components/ToastBar/ToastBar.tsx
packages/fuselage/src/styles/lengths.scss

[DSA-110]
[DSA-110]: https://rocketchat.atlassian.net/browse/DSA-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): `ToastBar` visual improvements

---

packages/fuselage/src/components/Slider/SliderThumb.tsx
packages/fuselage/src/components/Slider/SliderTrack.tsx

chore(fuselage): new `Slider` style

---

packages/fuselage/src/components/Modal/ModalIcon.tsx
packages/fuselage/src/components/Modal/ModalThumb.tsx

[DSAR-119](https://rocketchat.atlassian.net/browse/DSAR-119)
change `ModalThumb` default size to 28x28
[DSAR-119]: https://rocketchat.atlassian.net/browse/DSAR-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): `ModalThumb` size

---

packages/fuselage/src/components/AudioPlayer/AudioPlayer.tsx

chore(fuselage): Missing `aria-label` on `AudioPlayer`

---

packages/fuselage/src/components/States/States.styles.scss
packages/fuselage/src/components/States/States.tsx
packages/fuselage/src/components/States/StatesAction.tsx
packages/fuselage/src/components/States/StatesActions.tsx
packages/fuselage/src/components/States/StatesIcon.tsx
packages/fuselage/src/components/States/StatesSubtitle.tsx
packages/fuselage/src/components/States/StatesSuggestion.tsx
packages/fuselage/src/components/States/StatesSuggestionList.tsx
packages/fuselage/src/components/States/StatesSuggestionListItem.tsx
packages/fuselage/src/components/States/StatesSuggestionText.tsx
packages/fuselage/src/components/States/StatesTitle.tsx

chore(fuselage): Change `StatesTitle` to h3

---

packages/fuselage/src/Theme.ts
packages/fuselage/src/components/Message/MessageHighlight.tsx
packages/fuselage/src/components/Message/MessageMention.tsx
packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/index.tsx
packages/fuselage/src/styles/colors.scss

feat: Message Highlight and Mention components

---

packages/fuselage/src/components/Message/Messages.stories.tsx
packages/fuselage/src/components/Message/Messages.styles.scss

fix(fuselage): Message Highlight touching text

---

packages/fuselage/src/components/AudioPlayer/AudioPlayer.tsx
packages/fuselage/src/components/Slider/Slider.stories.tsx
packages/fuselage/src/components/Slider/Slider.tsx
packages/fuselage/src/components/Slider/SliderTrack.tsx

fix(fuselage): `AudioPlayer` responsiveness

---

packages/fuselage/src/components/Contextualbar/Contextualbar.tsx

chore(fuselage): Add missing inset prop to `Contextualbar`

---

packages/fuselage/src/components/Contextualbar/Contextualbar.tsx

[DSAR-142](https://rocketchat.atlassian.net/browse/DSAR-142)
[DSAR-142]: https://rocketchat.atlassian.net/browse/DSAR-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): Contextualbar max-width

---

packages/fuselage/src/components/Option/Option.tsx
packages/fuselage/src/components/Select/Listbox.tsx
packages/fuselage/src/components/Select/Select.styles.scss

fix(fuselage): use label on `Select`

---

packages/fuselage/src/components/Option/Option.stories.tsx
packages/fuselage/src/components/Option/Option.styles.scss
packages/fuselage/src/components/Option/Option.tsx

chore(fuselage): Remove spacedColumn from `Option` component

---

yarn.lock

chore(monorepo): security update `yaml`

---

packages/fuselage/src/components/Contextualbar/Contextualbar.tsx

revert(fuselage): Remove `maxWidth` from `Contextualbar`

---

packages/fuselage/src/components/Option/Option.stories.tsx
packages/fuselage/src/components/Option/Option.tsx

When using `Option` you can use the `gap` prop to add spacing to the left.
If the list is mixed (items **with and without** icons, you should add the gap to the elements without icons.

chore(fuselage): add `Option` gap

---

packages/fuselage/src/components/Message/Messages.styles.scss

chore(fuselage): Change message highlight alignment.

---

.github/workflows/cd.yml

chore(monorepo): Missing branch check on auto bump

---

packages/fuselage/src/components/Table/TableCell.tsx

fix(fuselage): `TableCell` children render

---

packages/fuselage/src/components/ButtonGroup/ButtonGroup.styles.scss

What:
- change pseudo-selector last/first-child to last/first-of-type
Why:
- if a sibling element is added to the DOM tree on the last position (e.g. a Menu dropdown), the pseudo-selector last-child gets lost

chore(fuselage): adjust `ButtonGroup` pseudo-selectors 

---

packages/fuselage/src/components/Dropdown/Dropdown.tsx
packages/fuselage/src/components/Dropdown/DropdownDesktop.tsx
packages/fuselage/src/components/Dropdown/DropdownDesktopWrapper.tsx
packages/fuselage/src/components/Dropdown/DropdownMobile.tsx
packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/Menu/V2/Menu.tsx
packages/fuselage/src/components/Menu/V2/MenuPopover.tsx
packages/fuselage/src/components/Menu/V2/helpers/helpers.ts

- fix `MenuV2` not closing on blur and esc

fix(fuselage): `MenuV2` behavior

---

packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/Menu/V2/Menu.tsx

fix: add pressed state on MenuButton

---

packages/fuselage/src/components/AudioPlayer/AudioPlayer.tsx

[DSAR-191](https://rocketchat.atlassian.net/browse/DSAR-191)
[DSAR-191]: https://rocketchat.atlassian.net/browse/DSAR-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): change `AudioPlayer` bg color

---

packages/fuselage/src/components/Select/SelectAria.tsx

[OC-1103](https://rocketchat.atlassian.net/browse/OC-1103)
[OC-1103]: https://rocketchat.atlassian.net/browse/OC-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): SelectAria position causing side effects

---

packages/fuselage/src/components/Menu/V2/Menu.tsx

chore(fuselage): update `MenuV2` className prop type

---

packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/Menu/V2/Menu.tsx
packages/fuselage/src/components/Menu/V2/MenuItem.tsx

- add MenuItem variants
- add Menu sizes
- add to storybook

chore(fuselage): `MenuV2` item variants

---

packages/fuselage/src/components/Menu/V2/Menu.tsx

fix(fuselage): `MenuV2` behavior on touch press

---

packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/styles/mixins/size.scss
packages/fuselage/src/styles/primitives/button.scss
packages/fuselage/src/styles/variables/buttons.scss

- resize button on active state
[DSAR-240]
[DSAR-240]: https://rocketchat.atlassian.net/browse/DSAR-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): Improve UX on `Button` click

---

packages/fuselage/src/components/AudioPlayer/AudioPlayer.tsx

chore(fuselage): `AudioPlayer` margins

---

packages/fuselage/src/components/Button/Button.stories.tsx
packages/fuselage/src/components/Button/Button.tsx

chore(fuselage): Improve `Icon` usage inside `Button`

---

packages/fuselage/src/components/Tabs/Tabs.stories.tsx
packages/fuselage/src/components/Tabs/Tabs.tsx
packages/fuselage/src/components/Tabs/index.tsx

chore(fuselage): Drop dot notation for `Tabs` component

---

packages/fuselage/src/components/Button/IconButton.tsx

- add animated class to IconButton

chore(fuselage): `IconButton` animated

---

packages/ui-kit/src/blocks/elements/TimePickerElement.ts

fix(uikit): `initialTime` prop time in `TimePicker` component

---

packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/Button.tsx
packages/fuselage/src/components/Button/IconButton.tsx
packages/fuselage/src/styles/primitives/box.scss

- change transition time to 0.18s 
- add transition ease-out to buttons style
- remove animation prop from button

chore(fuselage): `Button` transition tweaks

---

tools/build-icons/.eslintrc.json
tools/build-icons/build.mjs
tools/build-icons/font.mjs
tools/build-icons/glyphs.mjs
tools/build-icons/index.mjs

fix(icons): Build definition for `icons` package

---

packages/fuselage/src/components/States/States.stories.tsx
packages/fuselage/src/components/States/States.styles.scss
packages/fuselage/src/components/States/StatesLink.tsx
packages/fuselage/src/components/States/index.tsx

feat(fuselage): `StatesLink` Component

---

.github/workflows/cd.yml

chore(ci): Remove auto bump step

---

packages/ui-kit/src/blocks/LayoutBlock.ts

chore(ui-kit): Duplicated type in union

---

packages/fuselage/src/components/Accordion/Accordion.spec.tsx
packages/fuselage/src/components/Accordion/Accordion.tsx
packages/fuselage/src/components/Accordion/AccordionItem.tsx
packages/fuselage/src/components/Accordion/index.tsx

chore(fuselage): Fix `Accordion` a11y

---

packages/fuselage/src/components/Message/MessageGenericPreview/MessageGenericPreview.styles.scss
packages/fuselage/src/components/Message/MessageStatusIndicator/MessageStatusIndicator.styles.scss

fix(fuselage): css theme

---

packages/fuselage/src/components/Button/Button.stories.tsx
packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/Button.tsx

- improve `Button` stories
- remove resize animation on button click
- move text down 1px on button click: `translateY(1px)`

chore(fuselage): button click animation

---

packages/fuselage/src/components/Table/Table.spec.tsx
packages/fuselage/src/components/Table/Table.stories.tsx
packages/fuselage/src/components/Table/Table.styles.scss

- change `Table` background-color to transparent
- add a11y `Table ` tests

chore(fuselage): `Table` background-color 

---

packages/ui-kit/src/blocks/TextObject.ts
packages/ui-kit/src/blocks/WithTranslations.ts
packages/ui-kit/src/blocks/text/Markdown.ts
packages/ui-kit/src/blocks/text/PlainText.ts
packages/ui-kit/src/index.ts

refactor(ui-kit): Review some types

---

packages/fuselage/src/components/Field/Field.spec.tsx
packages/fuselage/src/components/Field/Field.stories.tsx
packages/fuselage/src/components/Field/Field.tsx
packages/fuselage/src/components/Field/FieldDescription.tsx
packages/fuselage/src/components/Field/FieldError.tsx
packages/fuselage/src/components/Field/FieldHint.tsx
packages/fuselage/src/components/Field/FieldLabel.tsx
packages/fuselage/src/components/Field/FieldLink.tsx
packages/fuselage/src/components/Field/FieldRow.tsx
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/Field/index.tsx
packages/fuselage/src/components/Label/Label.spec.tsx
packages/fuselage/src/components/Label/Label.styles.scss
packages/fuselage/src/components/Label/__snapshots__/Label.spec.tsx.snap
packages/fuselage/src/components/index.ts
packages/fuselage/src/helpers/WithErrorWrapper.tsx

chore(fuselage): `Field` & `Label` best practices adjustments

---

packages/fuselage/src/components/Field/Field.styles.scss

[DSAR-255](https://rocketchat.atlassian.net/browse/DSAR-255)
- change `FieldLabel` typography to p2b
[DSAR-255]: https://rocketchat.atlassian.net/browse/DSAR-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): change `FieldLabel` typography

---

packages/fuselage/src/components/Message/MessageReactions/MessageReactionAction.tsx

- change `MessageReactionAction` icon size to x16

fix(fuselage): `MessageReactionAction` icon size

---

packages/fuselage/src/components/CheckBox/CheckBox.spec.tsx
packages/fuselage/src/components/CheckBox/CheckBox.stories.tsx
packages/fuselage/src/components/CheckBox/CheckBox.tsx
packages/fuselage/src/components/CheckBox/__snapshots__/CheckBox.spec.tsx.snap
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/Label/Label.styles.scss
packages/fuselage/src/components/Label/Label.tsx
packages/fuselage/src/components/Label/__snapshots__/Label.spec.tsx.snap

chore(fuselage): Checkbox best practices adjustments

---

packages/fuselage-hooks/src/usePosition/index.spec.ts
packages/fuselage-hooks/src/usePosition/index.ts

fix(fuselage-hooks): usePosition fallback positioning

---

packages/fuselage/src/components/Select/Select.tsx
packages/fuselage/src/components/Select/SelectAria.tsx
packages/fuselage/src/components/Select/SelectFiltered.tsx
packages/layout/src/FormPageLayout/FormPageLayout.styles.tsx
packages/layout/src/HorizontalWizardLayout/HorizontalWizardLayout.tsx
packages/onboarding-ui/src/common/FormPageLayout.tsx
packages/onboarding-ui/src/common/PlanFeatureIcon.tsx
packages/onboarding-ui/src/pages/LoaderPage/LoaderPage.tsx
packages/onboarding-ui/src/pages/RedirectPage/RedirectPage.tsx
packages/onboarding-ui/src/pages/RegisterServerPage/RegisterServerPage.tsx
packages/onboarding-ui/src/pages/StandaloneServerPage/StandaloneServerPage.tsx

fix(onboarding-ui): Development warnings

---

packages/fuselage/.storybook/helpers.tsx
packages/fuselage/src/components/CheckBox/CheckBox.stories.tsx
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.spec.tsx
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.stories.tsx
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.tsx
packages/fuselage/src/components/ToggleSwitch/__snapshots__/ToggleSwitch.spec.tsx.snap

chore(fuselage): `ToggleSwitch` best practices adjustments

---

packages/fuselage/src/components/Message/MessageToolbox/MessageToolbox.styles.scss
packages/fuselage/src/components/Message/MessageToolbox/MessageToolboxWrapper.tsx

[TC-934](https://rocketchat.atlassian.net/browse/TC-934)
[TC-934]: https://rocketchat.atlassian.net/browse/TC-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): Prop to keep MessageToolbox visible.

---

packages/fuselage/src/components/Button/IconButton.stories.tsx
packages/fuselage/src/components/Button/IconButton.tsx
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap

fix(fuselage): Remove unnecessary `aria-label` fallback in `IconButton`

---

packages/ui-kit/README.md
packages/ui-kit/package.json
packages/ui-kit/src/blocks/layout/CalloutBlock.ts

fix(ui-kit): Remove `icons` package dependency in `ui-kit` package

---

packages/fuselage/src/components/Message/MessageGenericPreview/MessageGenericPreview.styles.scss
packages/fuselage/src/components/Message/MessageMetrics/MessageMetrics.styles.scss
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessage.styles.scss
packages/fuselage/src/components/Modal/Modal.styles.scss
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Tabs/Tabs.styles.scss

[DSAR-224](https://rocketchat.atlassian.net/browse/DSAR-224)
[DSAR-224]: https://rocketchat.atlassian.net/browse/DSAR-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): color a11y report changes

---

packages/fuselage/src/styles/primitives/button.scss

fix(fuselage): prevent button-disabled click animation

---

packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/Option/Option.styles.scss

fix(fuselage): `OptionInput` margins and alignment

---

.changeset/calm-suits-fail.md
.changeset/config.json
.changeset/dull-walls-bake.md
.changeset/early-spoons-return.md
.changeset/eighty-fans-fold.md
.changeset/funny-pets-grow.md
.changeset/honest-eels-complain.md
.changeset/kind-lions-love.md
.changeset/little-stingrays-jump.md
.changeset/moody-dingos-rest.md
.changeset/neat-fishes-confess.md
.changeset/nice-cows-relax.md
.changeset/odd-hornets-sing.md
.changeset/old-terms-reflect.md
.changeset/plenty-donuts-poke.md
.changeset/real-pots-heal.md
.changeset/shy-cows-sort.md
.changeset/silver-schools-allow.md
.changeset/sour-bears-rest.md
.changeset/sour-dolphins-breathe.md
.changeset/stale-hairs-mate.md
.changeset/stupid-emus-hunt.md
.changeset/sweet-bulldogs-press.md
.changeset/tall-eels-cover.md
.changeset/two-lies-sin.md
.changeset/wicked-tools-relax.md
.github/workflows/cd.yml
.github/workflows/codeql.yml

chore: Improve continuous delivery

---

.changeset/famous-students-sin.md
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelect.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelectFiltered.stories.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedMultiSelectFiltered.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.tsx
packages/fuselage/src/components/PaginatedSelect/PaginatedSelectFiltered.stories.tsx
packages/fuselage/src/components/PaginatedSelect/index.ts

fix(fuselage): Memory leak in `PaginatedMultiSelect`

---

packages/fuselage/src/components/Sidebar/Sidebar.stories.tsx
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Tabs/Tabs.styles.scss

- add `text-decoration: none` to sidebar links
- fix tabs color

chore(fuselage): Sidebar links style

---

.changeset/hot-bears-shout.md
packages/fuselage/src/styles/colors.scss
packages/fuselage/src/styles/primitives/selection-button.scss
packages/fuselage/src/styles/variables/button-colors.scss
packages/fuselage/src/styles/variables/input-colors.scss

[DSAR-275](https://rocketchat.atlassian.net/browse/DSAR-275)
previous:
new:
[DSAR-275]: https://rocketchat.atlassian.net/browse/DSAR-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): improve focus state color

---

.changeset/shaggy-deers-impress.md
packages/fuselage/.storybook/helpers.tsx
packages/fuselage/src/components/CheckBox/CheckBox.stories.tsx
packages/fuselage/src/components/CheckBox/CheckBox.tsx
packages/fuselage/src/components/CheckBox/__snapshots__/CheckBox.spec.tsx.snap
packages/fuselage/src/components/RadioButton/RadioButton.spec.tsx
packages/fuselage/src/components/RadioButton/RadioButton.tsx
packages/fuselage/src/components/RadioButton/__snapshots__/RadioButton.spec.tsx.snap
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.stories.tsx
packages/fuselage/src/components/ToggleSwitch/ToggleSwitch.tsx
packages/fuselage/src/components/ToggleSwitch/__snapshots__/ToggleSwitch.spec.tsx.snap

Pseudo-states helper classes (`is-focused`, `is-active`, etc) were not being passed to the correct element, after the components refactor
- pass className to input label wrapper
- fix storybook table helper a11y violation, to be able to add States story to the tests
- update snapshots

fix(fuselage): className prop drilling improvements on `CheckBox`, `ToggleSwitch` and `RadioButton`

---

.changeset/hip-bats-stare.md
packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/forms/AdminInfoForm/AdminInfoForm.tsx
packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx

- Fields receiving an asterisk as required fields
- Proceed Button is not disabled only at the validation of all required fields
NBJ-374

feat(onboarding-ui): Required fields adjustments

---

.changeset/stupid-mayflies-look.md
packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/flows/SelfHostedRegistration/stories.tsx
packages/onboarding-ui/src/forms/AwaitConfirmationForm/AwaitConfirmationForm.spec.tsx
packages/onboarding-ui/src/forms/AwaitConfirmationForm/AwaitConfirmationForm.stories.tsx
packages/onboarding-ui/src/forms/AwaitConfirmationForm/AwaitConfirmationForm.tsx
packages/onboarding-ui/src/forms/AwaitConfirmationForm/index.ts
packages/onboarding-ui/src/pages/AwaitingConfirmationPage/AwaitingConfirmationPage.spec.tsx
packages/onboarding-ui/src/pages/AwaitingConfirmationPage/AwaitingConfirmationPage.tsx

refactor(onboarding-ui): Rewrite `AwaitingConfirmationPage` page

---

packages/fuselage/src/components/FieldGroup/FieldGroup.stories.tsx
packages/fuselage/src/components/Modal/Modal.stories.tsx
packages/layout/src/HorizontalWizardLayout/HorizontalWizardLayout.stories.tsx
packages/layout/src/VerticalWizardLayout/VerticalWizardLayout.stories.tsx
packages/onboarding-ui/src/forms/AdminInfoForm/AdminInfoForm.tsx
packages/onboarding-ui/src/forms/CreateCloudWorkspaceForm/CreateCloudWorkspaceForm.tsx
packages/onboarding-ui/src/forms/CreateFirstMemberForm/CreateFirstMemberForm.tsx
packages/onboarding-ui/src/forms/CreateNewPassword/CreateNewPassword.tsx
packages/onboarding-ui/src/forms/LoginForm/LoginForm.tsx
packages/onboarding-ui/src/forms/NewAccountForm/NewAccountForm.tsx
packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx
packages/onboarding-ui/src/forms/RequestTrialForm/RequestTrialForm.tsx
packages/onboarding-ui/src/forms/ResetPasswordForm/ResetPasswordForm.tsx
packages/onboarding-ui/src/forms/TotpForm/TotpForm.tsx

replace deprecated Field assigned subcomponents:
`Field.Group` -> `FieldGroup`
`Field.Hint` -> `FieldHint`
`Field.Label`-> `FieldLabel`
`Field.Row` -> `FieldRow`

refactor: replace `Field.[SUBCOMPONENT]` in favor of named imports

---

.changeset/big-apes-agree.md
.changeset/hip-bats-stare.md
.changeset/popular-adults-hope.md
.changeset/stupid-mayflies-look.md
packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/.storybook/main.ts
packages/onboarding-ui/package.json
packages/onboarding-ui/src/forms/AdminInfoForm/AdminInfoForm.tsx
packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx
yarn.lock

- add required fields validation message
- a11y form best practices
forms changed:
- `AdminInfoForm`
- `OrganizationInfoForm`
- `RegisterServerForm`

feat(onboarding-ui): a11y forms improvements

---

packages/fuselage/src/components/Sidebar/Sidebar.stories.tsx
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

[DSAR-283](https://rocketchat.atlassian.net/browse/DSAR-283)
[DSAR-283]: https://rocketchat.atlassian.net/browse/DSAR-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(fuselage): change sidebar-item focus border

---

.changeset/gorgeous-horses-grow.md
packages/onboarding-ui/.i18n/en.i18n.json
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx

feat(onboarding-ui): Update agreements message on `RegisterServerForm`

---

.changeset/cuddly-flowers-crash.md
packages/fuselage/src/components/Contextualbar/ContextualbarAction.tsx

[DSAR-296]
[DSAR-296]: https://rocketchat.atlassian.net/browse/DSAR-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): `ContextualbarAction` size

---

.changeset/selfish-scissors-sit.md
packages/fuselage/src/components/Field/Field.styles.scss
packages/fuselage/src/components/States/States.styles.scss
packages/fuselage/src/styles/primitives/traits/rich-text.scss

fix(fuselage): Remove underline prevention on anchor elements

---

.changeset/cuddly-cars-jam.md
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

[DSAR-283](https://rocketchat.atlassian.net/browse/DSAR-283)
[DSAR-283]: https://rocketchat.atlassian.net/browse/DSAR-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): change `SidebarItem` focus color

---

.changeset/selfish-plants-divide.md
packages/fuselage/src/components/Tag/Tag.stories.tsx
packages/fuselage/src/components/Tag/Tag.tsx

feat(fuselage): option to use `Tag` as link

---

.changeset/many-crabs-hope.md
packages/fuselage/src/components/Sidebar/Sidebar.stories.tsx
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/components/Sidebar/SidebarBanner.tsx

- Changed text color from grey to white.
- Added a new property `addon`. 
Just like the property of same name available on `TextBox` component, this property allows you to add a react element to a specific slot in the component.
Before:
After:
With addon:
With addon and onClose:

feat(fuselage): Added property `addon` to SidebarBanner and updated styles

---

.changeset/nine-tomatoes-appear.md
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

fix(fuselage): `SidebarItem` margins

---

.changeset/gentle-carrots-buy.md
packages/fuselage/src/styles/primitives/traits/rich-text.scss

[DSAR-316](https://rocketchat.atlassian.net/browse/DSAR-316)
[DSAR-316]: https://rocketchat.atlassian.net/browse/DSAR-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): change `link:active` color

---

.changeset/shy-weeks-guess.md
packages/fuselage/src/Theme.ts
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/fuselage/src/styles/colors.scss

[DSAR-299](https://rocketchat.atlassian.net/browse/DSAR-299)
[DSAR-299]: https://rocketchat.atlassian.net/browse/DSAR-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): New `surface-sidebar` token

---

.changeset/clever-brooms-hear.md
packages/fuselage/src/components/Callout/Callout.styles.scss

- change `Callout` text color to font-default

fix(fuselage): change `Callout` text color

---

.changeset/selfish-tigers-melt.md
packages/fuselage/src/components/Button/Button.stories.tsx
packages/fuselage/src/components/Button/Button.styles.scss
packages/fuselage/src/components/Button/Button.tsx
packages/fuselage/src/styles/primitives/button.scss

[DSAR-313](https://rocketchat.atlassian.net/browse/DSAR-313)
[DSAR-313]: https://rocketchat.atlassian.net/browse/DSAR-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): add loading state to `Button`

---

.changeset/tame-bikes-reflect.md
packages/fuselage/src/components/Field/Field.stories.tsx
packages/fuselage/src/components/Field/FieldLabelInfo.tsx
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/Field/index.tsx
packages/fuselage/src/components/Label/Label.stories.tsx
packages/fuselage/src/components/Label/Label.styles.scss
packages/fuselage/src/components/Label/LabelInfo.tsx
packages/fuselage/src/components/Label/__snapshots__/Label.spec.tsx.snap

[DSAR-315](https://rocketchat.atlassian.net/browse/DSAR-315)
[DSAR-315]: https://rocketchat.atlassian.net/browse/DSAR-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): create `LabelInfo` component

---

.changeset/curly-bears-wait.md
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

[DSAR-346](https://rocketchat.atlassian.net/browse/DSAR-346)
[DSAR-346]: https://rocketchat.atlassian.net/browse/DSAR-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): update `SidebarItem` highlighted weight

---

packages/onboarding-ui/src/common/AgreeTermsField.tsx
packages/onboarding-ui/src/flows/SelfHostedRegistration/stories.tsx
packages/onboarding-ui/src/forms/AwaitConfirmationForm/AwaitConfirmationForm.tsx
packages/onboarding-ui/src/forms/RegisterOfflineForm/RegisterOfflineForm.spec.tsx
packages/onboarding-ui/src/forms/RegisterOfflineForm/RegisterOfflineForm.tsx
packages/onboarding-ui/src/forms/RegisterOfflineForm/steps/CopyStep.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.tsx
packages/onboarding-ui/src/pages/RegisterOfflinePage/RegisterOfflinePage.spec.tsx
packages/onboarding-ui/src/pages/RegisterOfflinePage/RegisterOfflinePage.tsx

- space in agreement label
- callback function to offline copy step button
- security code and label displayed in block
NBJ-555

fix(onboarding-ui): Ui adjustments and improvements

---

.changeset/shaggy-lobsters-greet.md
packages/fuselage/src/components/CardGroup/CardGroup.styles.scss

fix(fuselage): `CardGroup` wrap margins

---

packages/fuselage/src/components/Card/Card.styles.scss
packages/fuselage/src/components/Card/CardBody.tsx
packages/fuselage/src/components/CardGrid/CardGrid.tsx

chore: `Card` tweaks

---

.changeset/slimy-houses-smile.md
packages/fuselage/src/components/Card/Card.stories.tsx
packages/fuselage/src/components/Card/Card.styles.scss
packages/fuselage/src/components/Card/Card.tsx
packages/fuselage/src/components/Card/__snapshots__/Card.spec.tsx.snap

feat(fuselage): add `Card` hero variant

---

.changeset/country-select-input.md
packages/onboarding-ui/src/forms/OrganizationInfoForm/OrganizationInfoForm.tsx

The country Select from Organization Info page had some inconsistencies and it was breaking some times, since the SelectFilter it's using the `SelectLegacy` I replaced with the new `Select` component.
**current code w/ SelectLegacy:** 
**new code w/ Select component**
https://rocketchat.atlassian.net/browse/WM-213

fix: Country Select not closing

---

.changeset/large-shirts-pull.md
packages/fuselage/src/components/FramedIcon/FramedIcon.spec.tsx
packages/fuselage/src/components/FramedIcon/FramedIcon.stories.tsx
packages/fuselage/src/components/FramedIcon/FramedIcon.styles.scss
packages/fuselage/src/components/FramedIcon/FramedIcon.tsx
packages/fuselage/src/components/FramedIcon/__snapshots__/FramedIcon.spec.tsx.snap
packages/fuselage/src/components/FramedIcon/index.ts
packages/fuselage/src/components/index.scss
packages/fuselage/src/components/index.ts

[DSAR-323](https://rocketchat.atlassian.net/browse/DSAR-323)
[DSAR-323]: https://rocketchat.atlassian.net/browse/DSAR-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): `FramedIcon` new component

---

packages/fuselage/src/components/Card/Card.stories.tsx
packages/fuselage/src/components/Card/Card.styles.scss
packages/fuselage/src/components/Card/Card.tsx
packages/fuselage/src/components/Card/CardTitle.tsx
packages/fuselage/src/components/Card/__snapshots__/Card.spec.tsx.snap
packages/fuselage/src/components/CardGrid/CardGrid.stories.tsx
packages/fuselage/src/components/CardGrid/__snapshots__/CardGrid.spec.tsx.snap
packages/fuselage/src/components/CardGroup/CardGroup.stories.tsx
packages/fuselage/src/components/CardGroup/CardGroup.tsx
packages/fuselage/src/components/CardGroup/__snapshots__/CardGroup.spec.tsx.snap

chore(fuselage): `Card` improvements

---

.changeset/many-cobras-whisper.md
packages/fuselage/src/components/FramedIcon/FramedIcon.tsx

fix(fuselage): `FramedIcon` HTMLAttributes props

---

.changeset/brown-rabbits-pay.md
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.tsx
packages/fuselage/src/components/Message/MessageToolbox/MessageToolbox.styles.scss
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/mixins.scss
packages/fuselage/src/styles/mixins/shadows.scss

feat(fuselage): Add `Message` focus style

---

.changeset/silver-news-share.md
packages/fuselage/src/components/ButtonGroup/ButtonGroup.styles.scss

fix(fuselage): Add `flexGrow` for stretch variation

---

.changeset/four-ears-argue.md
packages/fuselage/src/components/Card/Card.styles.scss

[DSAR-447](https://rocketchat.atlassian.net/browse/DSAR-447)
[DSAR-447]: https://rocketchat.atlassian.net/browse/DSAR-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): change `card-horizontal` row gap

---

.changeset/tame-actors-begin.md
packages/fuselage/src/components/Bubble/Bubble.stories.tsx
packages/fuselage/src/components/Bubble/Bubble.styles.scss
packages/fuselage/src/components/Bubble/Bubble.tsx
packages/fuselage/src/components/Bubble/BubbleButton.tsx
packages/fuselage/src/components/Bubble/BubbleItem.tsx
packages/fuselage/src/components/Bubble/__snapshots__/Bubble.spec.tsx.snap

- add `secondary` variation
- add `small` variation
bubble with no action: 
- make it not a button
- remove interaction styles (hover, active, ...)

feat(fuselage): `Bubble` variations

---

.changeset/dirty-brooms-double.md
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.spec.tsx
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.stories.tsx
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss
packages/fuselage/src/components/Message/MessageSystem/__snapshots__/MessageSystem.spec.tsx.snap

fix(fuselage): `MessageSystem` time fontScale

---

.changeset/popular-dancers-remember.md
packages/fuselage/src/components/Popover/Popover.spec.tsx
packages/fuselage/src/components/Popover/Popover.stories.tsx
packages/fuselage/src/components/Popover/Popover.tsx
packages/fuselage/src/components/Popover/__snapshots__/Popover.spec.tsx.snap
packages/fuselage/src/components/Popover/index.ts
packages/fuselage/src/components/Select/SelectAria.tsx
packages/fuselage/src/components/index.ts

feat(fuselage): `Popover`

---

.changeset/silver-pans-own.md
packages/fuselage/src/components/Message/mixins.scss

fix(fuselage): Prevent focus state on clicking in `Messages`

---

yarn.lock

chore(deps): bump semver from 2 || 3 || 4 || 5 to 5.7.2

---

.changeset/warm-ducks-walk.md
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss
packages/fuselage/src/components/Message/Messages.styles.scss
packages/fuselage/src/components/Message/mixins.scss
packages/fuselage/src/components/Tag/Tag.spec.tsx
packages/fuselage/src/components/Tag/Tag.styles.scss
packages/fuselage/src/components/Tag/__snapshots__/Tag.spec.tsx.snap
packages/fuselage/src/styles/mixins/all.scss
packages/fuselage/src/styles/mixins/templates.scss

feat(fuselage): Adds `Tag` focus state

---

.changeset/early-cycles-serve.md
packages/fuselage/src/components/Message/MessageToolbar/MessageToolbar.styles.scss
packages/fuselage/src/components/Message/MessageToolbar/MessageToolbarWrapper.tsx

fix(fuselage): `MessageToolbarWrapper` visibility

---

.changeset/yellow-jokes-rest.md
packages/fuselage/src/components/Contextualbar/Contextualbar.spec.tsx
packages/fuselage/src/components/Contextualbar/Contextualbar.stories.tsx
packages/fuselage/src/components/Contextualbar/Contextualbar.tsx
packages/fuselage/src/components/Contextualbar/ContextualbarFooter.tsx
packages/fuselage/src/components/Contextualbar/ContextualbarHeader.tsx
packages/fuselage/src/components/Contextualbar/ContextualbarSkeleton.tsx
packages/fuselage/src/components/Contextualbar/ContextualbarTitle.tsx
packages/fuselage/src/components/Contextualbar/__snapshots__/Contextualbar.spec.tsx.snap

fix(fuselage): `Contextualbar` elements syntax

---

.changeset/quiet-ducks-scream.md
packages/fuselage/src/components/Bubble/BubbleButton.tsx
packages/fuselage/src/components/Bubble/__snapshots__/Bubble.spec.tsx.snap

[DSAR-480](https://rocketchat.atlassian.net/browse/DSAR-480)
[DSAR-480]: https://rocketchat.atlassian.net/browse/DSAR-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): remove margin inline end from bubble icon

---

.changeset/short-waves-double.md
packages/fuselage/src/components/Contextualbar/Contextualbar.tsx

feat(fuselage): Add `forwardRef` on `Contextualbar`

---

.changeset/fuzzy-pumpkins-beg.md
packages/fuselage/src/components/PaginatedSelect/PaginatedSelect.tsx

Add missing renderItem property on PaginatedSelect that allows options customization.

fix(fuselage): Add missing renderItem property on PaginatedSelect

---

.changeset/shiny-hats-own.md

chore: Missing changeset

---

.changeset/weak-oranges-impress.md
packages/fuselage/src/components/AutoComplete/AutoComplete.stories.tsx
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx
packages/fuselage/src/components/AutoComplete/__snapshots__/AutoComplete.spec.tsx.snap

fix(fuselage): show `AutoComplete` placeholder

---

packages/fuselage/src/components/Message/MessageBody.tsx
packages/fuselage/src/components/Message/MessageContainer.tsx
packages/fuselage/src/components/Message/MessageContainerFixed.tsx
packages/fuselage/src/components/Message/MessageEmoji.tsx
packages/fuselage/src/components/Message/MessageEmojiBase.tsx
packages/fuselage/src/components/Message/MessageHeader.tsx
packages/fuselage/src/components/Message/MessageLeftContainer.tsx
packages/fuselage/src/components/Message/MessageName.tsx
packages/fuselage/src/components/Message/MessageNameContainer.tsx
packages/fuselage/src/components/Message/MessageReactions/MessageReactionEmoji.tsx
packages/fuselage/src/components/Message/MessageRole.tsx
packages/fuselage/src/components/Message/MessageRoles.tsx
packages/fuselage/src/components/Message/MessageTimestamp.tsx
packages/fuselage/src/components/Message/MessageUsername.tsx
packages/fuselage/src/components/Message/ThreadMessage/ThreadMessageEmoji.tsx

chore(fuselage): Messages's components incorrect types

---

packages/fuselage/README.md

chore(fuselage): Update docs

---

.changeset/breezy-windows-float.md
packages/fuselage-tokens/package.json

fix(fuselage-tokens): change dist files list to be published

---

.changeset/bright-meals-type.md
packages/fuselage/src/components/AutoComplete/AutoComplete.tsx

fix(fuselage): Remove `option` role from `Autocomplete` options component

---

.changeset/mighty-gifts-impress.md
packages/fuselage/src/components/ButtonGroup/ButtonGroup.styles.scss

fix(fuselage): remove margins from `ButtonGroup` first and last items

---

packages/fuselage/src/components/Menu/V2/Menu.stories.tsx
packages/fuselage/src/components/NavBar/NavBar.spec.tsx
packages/fuselage/src/components/NavBar/NavBar.stories.tsx
packages/fuselage/src/components/NavBar/NavBar.styles.scss
packages/fuselage/src/components/NavBar/NavBar.tsx
packages/fuselage/src/components/NavBar/NavBarDivider.tsx
packages/fuselage/src/components/NavBar/NavBarGroup.tsx
packages/fuselage/src/components/NavBar/NavBarItem.tsx
packages/fuselage/src/components/NavBar/NavBarSection.tsx
packages/fuselage/src/components/NavBar/__snapshots__/NavBar.spec.tsx.snap
packages/fuselage/src/components/NavBar/index.ts
packages/fuselage/src/components/index.scss
packages/fuselage/src/components/index.ts

[SIDE-2](https://rocketchat.atlassian.net/browse/SIDE-2)
[DSAR-482]: https://rocketchat.atlassian.net/browse/DSAR-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIDE-2]: https://rocketchat.atlassian.net/browse/SIDE-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): new set of `NavBar` components

---

.changeset/green-balloons-move.md
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss

[DSAR-487](https://rocketchat.atlassian.net/browse/DSAR-487)
[DSAR-487]: https://rocketchat.atlassian.net/browse/DSAR-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): add `MessageSystem` missing colors

---

.changeset/shaggy-foxes-explode.md
packages/fuselage/src/components/Bubble/BubbleButton.tsx
packages/fuselage/src/components/Bubble/__snapshots__/Bubble.spec.tsx.snap

fix(fuselage): `Bubble` missing font-family

---

.changeset/poor-toes-knock.md
packages/fuselage/src/components/Button/IconButton.stories.tsx
packages/fuselage/src/components/Button/IconButton.tsx

fix(fuselage): `IconButton` with badge positioning

---

.changeset/red-tips-joke.md
packages/fuselage/src/components/Modal/Modal.spec.tsx
packages/fuselage/src/components/Modal/Modal.tsx
packages/fuselage/src/components/Modal/ModalClose.tsx
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap

fix(fuselage): Modal components missing some a11y props

---

.changeset/proud-kangaroos-enjoy.md
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss

fix(fuselage): `SidebarItem` missing badge vertical alignment

---

.changeset/orange-zoos-study.md
packages/fuselage/src/components/Option/OptionContent.tsx

fix(fuselage): `OptionContent` props type

---

packages/eslint-config-alt/minimal/index.js
packages/fuselage/.storybook/DocsContainer.tsx
packages/fuselage/src/components/Menu/V2/Menu.tsx
packages/fuselage/src/components/Menu/V2/index.ts
packages/fuselage/src/components/Menu/V2/stately/MenuItem.tsx
packages/fuselage/src/components/Menu/V2/stately/MenuSection.tsx
packages/fuselage/src/components/Menu/V2/stately/PartialNode.tsx

refactor(fuselage): `MenuV2` display names

---

.github/workflows/ci-pr.yml

It adds the param to cancel previous in progress runs, if there's a new commit on a pull request.

chore: Add `cancel-in-progress` concurrency param on CI

---

packages/fuselage/src/components/Sidebar/SidebarDivider.tsx
packages/fuselage/src/components/Sidebar/TopBar/__snapshots__/TopBar.spec.tsx.snap

chore: change `SidebarDivider` margin unit

---

package.json
turbo.json
yarn.lock

Upgrades Turborepo to major version 2.

chore: Upgrade Turborepo

---

.changeset/real-seas-melt.md
packages/fuselage/src/components/Accordion/Accordion.styles.scss

According to the [Design system](https://www.figma.com/design/CcKhUgDMecW1xvlAtV86o1/Design-system---Web-%26-desktop?node-id=367-13924&m=dev) the accordion color token should be `titles-labels`

fix(fuselage): change `Accordion` color token

---

.changeset/thin-chairs-wash.md
packages/fuselage/src/components/Bubble/Bubble.stories.tsx
packages/fuselage/src/components/Bubble/Bubble.styles.scss
packages/fuselage/src/components/Bubble/__snapshots__/Bubble.spec.tsx.snap

fix(fuselage): `Bubble` missing text truncation

---

.changeset/popular-beers-run.md
packages/fuselage/src/components/Bubble/Bubble.styles.scss

fix(fuselage): `Bubble` missing overflow property

---

.changeset/sweet-sheep-film.md
packages/fuselage/src/components/Field/Field.styles.scss
packages/fuselage/src/components/InputBox/InputBox.styles.scss

As defined here:
https://www.figma.com/design/CcKhUgDMecW1xvlAtV86o1/Design-system---Web-%26-desktop?node-id=18230-33649&t=fBAVAjaCZZ96WXXB-4
Jira task: [CONN-336](https://rocketchat.atlassian.net/browse/CONN-336?atlOrigin=eyJpIjoiYTFkNGE1ZjM2ZWNkNDlhZmI4YWNiYWMwZmRmMDM1NDQiLCJwIjoiaiJ9)
[CONN-336]: https://rocketchat.atlassian.net/browse/CONN-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): update `InputBox` and `Field` typography

---

.github/workflows/cd.yml
.github/workflows/ci-pr.yml

chore: bump upload-artifact@v3

---

.github/workflows/cd.yml
.github/workflows/ci-pr.yml

chore: bump actions

---

.changeset/tame-poems-drop.md
.github/workflows/cd.yml
.github/workflows/ci-pr.yml
packages/fuselage/src/components/Sidebar/Sidebar.styles.scss
packages/layout/.storybook/main.ts

fix(fuselage): color sidebar highlighted

---

.github/workflows/cd.yml
.github/workflows/ci-pr.yml
package.json
turbo.json
yarn.lock

chore: bump turbo

---

.github/workflows/cd.yml
.github/workflows/ci-pr.yml
package.json
turbo.json
yarn.lock

Reverts RocketChat/fuselage#1451

Revert "chore: bump turbo"

---

.changeset/chilly-rockets-bow.md
packages/fuselage/src/components/AutoComplete/__snapshots__/AutoComplete.spec.tsx.snap
packages/fuselage/src/components/Avatar/__snapshots__/Avatar.spec.tsx.snap
packages/fuselage/src/components/Callout/__snapshots__/Callout.spec.tsx.snap
packages/fuselage/src/components/Card/__snapshots__/Card.spec.tsx.snap
packages/fuselage/src/components/CardGroup/__snapshots__/CardGroup.spec.tsx.snap
packages/fuselage/src/components/CheckBox/__snapshots__/CheckBox.spec.tsx.snap
packages/fuselage/src/components/Contextualbar/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/ContextualbarV2/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/Field/__snapshots__/Field.spec.tsx.snap
packages/fuselage/src/components/Message/MessageMetrics/__snapshots__/MessageMetrics.spec.tsx.snap
packages/fuselage/src/components/Message/MessageReactions/__snapshots__/MessageReactions.spec.tsx.snap
packages/fuselage/src/components/Message/MessageToolbar/__snapshots__/MessageToolbar.spec.tsx.snap
packages/fuselage/src/components/Modal/__snapshots__/Modal.spec.tsx.snap
packages/fuselage/src/components/NavBar/__snapshots__/NavBar.spec.tsx.snap
packages/fuselage/src/components/PasswordInput/__snapshots__/PasswordInput.spec.tsx.snap
packages/fuselage/src/components/RadioButton/__snapshots__/RadioButton.spec.tsx.snap
packages/fuselage/src/components/SelectInput/__snapshots__/SelectInput.spec.tsx.snap
packages/fuselage/src/components/Sidebar/TopBar/__snapshots__/TopBar.spec.tsx.snap
packages/fuselage/src/components/Table/__snapshots__/Table.spec.tsx.snap
packages/fuselage/src/components/Tag/__snapshots__/Tag.spec.tsx.snap
packages/fuselage/src/components/ToastBar/__snapshots__/ToastBar.spec.tsx.snap
packages/fuselage/src/components/ToggleSwitch/__snapshots__/ToggleSwitch.spec.tsx.snap
packages/fuselage/src/helpers/appendClassName.ts

It fixes a bug that adds an extra whitespace when concatenating class names with `appendClassName`.

fix(fuselage): Skip empty strings when appending class name

---

.changeset/lazy-roses-kick.md
packages/fuselage/src/components/Contextualbar/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/ContextualbarV2/__snapshots__/Contextualbar.spec.tsx.snap
packages/fuselage/src/components/Skeleton/Skeleton.spec.tsx
packages/fuselage/src/components/Skeleton/Skeleton.stories.tsx
packages/fuselage/src/components/Skeleton/Skeleton.styles.scss
packages/fuselage/src/components/Skeleton/Skeleton.tsx
packages/fuselage/src/components/Skeleton/__snapshots__/Skeleton.spec.tsx.snap

It simplifies `Skeleton` by replacing the dependency on `Box` with `StylingBox`. Additionally, it implements a new background animation.

feat(fuselage): Lighter `Skeleton`

---

packages/fuselage-tokens/.eslintrc
packages/fuselage-tokens/.eslintrc.js
packages/fuselage-tokens/build.js
packages/fuselage-tokens/config.js
packages/fuselage-tokens/package.json
packages/fuselage-tokens/src/index.js
packages/fuselage-tokens/typograhy.js
tools/build-design-tokens/index.mjs
tools/tools-utils/source.mjs
yarn.lock

chore(fuselage-tokens): Upgrade `style-dictionary`

---

.changeset/gentle-eagles-run.md
packages/fuselage/src/components/Select/SelectAria.tsx

fix(fuselage): `Select` disabled opening with keyboard

---

.changeset/hungry-rings-develop.md
packages/fuselage/src/components/Card/Card.styles.scss

Reverts RocketChat/fuselage#1488

chore: Revert fix(fuselage): Change `Card` vertical-gap to 32px

---

.changeset/hip-bananas-obey.md
packages/fuselage/src/components/CodeSnippet/CodeSnippet.spec.tsx
packages/fuselage/src/components/CodeSnippet/CodeSnippet.styles.scss
packages/fuselage/src/components/CodeSnippet/CodeSnippet.tsx
packages/fuselage/src/components/CodeSnippet/__snapshots__/CodeSnippet.spec.tsx.snap

fix(fuselage): `CodeSnippet` inheriting `code` css styles

---

.changeset/warm-points-count.md
packages/fuselage/src/components/Message/Messages.styles.scss

feat(fuselage): Update selected message background

---

.changeset/eighty-parrots-join.md
packages/fuselage/src/components/Message/MessageSystem/MessageSystem.styles.scss

feat(fuselage): Update selected system message background

---

.changeset/empty-ads-heal.md
packages/fuselage/src/components/Skeleton/Skeleton.tsx

fix(fuselage): `Skeleton` missing HTML attributes in type

---

.changeset/healthy-dryers-admire.md
packages/fuselage/src/components/SidebarV2/Sidebar.styles.scss
packages/fuselage/src/components/SidebarV2/SidebarFooter/SidebarFooter.styles.scss

- add calc to the `sidebar-v2-collapse-group` padding - [SIDE-220](https://rocketchat.atlassian.net/browse/SIDE-220)
- change `SidebarV2Footer` height to min-height
[SIDE-220]: https://rocketchat.atlassian.net/browse/SIDE-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): `SidebarV2` styles

---

packages/fuselage-hooks/package.json
packages/fuselage-toastbar/package.json
packages/fuselage/package.json
packages/layout/package.json
packages/logo/package.json
packages/onboarding-ui/package.json
yarn.lock

chore: Upgrade `@types/react`

---

.changeset/heavy-fishes-sing.md
packages/fuselage/src/components/Slider/Slider.tsx

- `Slider` accessing default value before initialization

fix(fuselage): broken `Slider` multi thumb 

---

packages/fuselage-hooks/README.md
packages/fuselage-hooks/package.json
yarn.lock

Package was missing the emitter as dependency.

chore(fuselage-hooks): Add `@rocket.chat/emitter` as peer and dev dependency

---

packages/fuselage-hooks/src/useStorage.ts

refactor: use `useSyncExternalStore` in favor of `useState` in `useXyzStorage` hooks

---

.changeset/proud-hotels-bake.md
packages/onboarding-ui/.jest/setup.ts
packages/onboarding-ui/src/common/AgreeTermsField.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/RegisterServerForm.spec.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/__snapshots__/RegisterServerForm.spec.tsx.snap

[CORE-1015](https://rocketchat.atlassian.net/browse/CORE-1015)
[CORE-1015]: https://rocketchat.atlassian.net/browse/CORE-1015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onboarding-ui): Alignment on Register server step

---

.changeset/shiny-monkeys-swim.md
packages/layout/src/components/FormPageLayout/Form.tsx
packages/layout/src/components/FormPageLayout/__snapshots__/FormPageLayout.spec.tsx.snap
packages/layout/src/layouts/HorizontalWizardLayout/__snapshots__/HorizontalWizardLayout.spec.tsx.snap
packages/layout/src/layouts/VerticalWizardLayout/__snapshots__/VerticalWizardLayout.spec.tsx.snap
packages/onboarding-ui/.storybook/preview.tsx
packages/onboarding-ui/src/forms/RegisterServerForm/__snapshots__/RegisterServerForm.spec.tsx.snap

[ARCH-1583](https://rocketchat.atlassian.net/browse/ARCH-1583)
[ARCH-1583]: https://rocketchat.atlassian.net/browse/ARCH-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(layout): add missing tokens to layout `Form`

---

.changeset/light-badgers-walk.md
packages/fuselage/src/components/Menu/V2/Menu.tsx
packages/fuselage/src/components/NavBar/__snapshots__/NavBar.spec.tsx.snap

fix(fuselage): MenuV2 button should receive label

---

.changeset/shaky-readers-wish.md
packages/fuselage/src/components/Tag/Tag.styles.scss

[SIDE2-78]
[SIDE2-78]: https://rocketchat.atlassian.net/browse/SIDE2-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fuselage): `Tag` default colors

---

.changeset/cute-mammals-go.md
packages/fuselage-hooks/src/index.ts
packages/fuselage-hooks/src/useButtonPattern.spec.ts
packages/fuselage-hooks/src/useButtonPattern.ts
packages/fuselage/src/components/Banner/Banner.tsx

feat(fuselage): Introduce `useButtonPattern`

---

.changeset/tired-colts-hunt.md
packages/fuselage/src/components/Sidepanel/Sidepanel.styles.scss

[SIDE2-110]
[SIDE2-110]: https://rocketchat.atlassian.net/browse/SIDE2-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(fuselage): Update SidePanel header title scale and color

---

packages/fuselage-forms/package.json
packages/fuselage-forms/typedoc.json
yarn.lock

chore(fuselage-forms): Remove typedoc script

---

.changeset/four-baboons-float.md
packages/fuselage/src/components/SidebarV2/SidebarItem/SidebarItem.styles.scss
packages/fuselage/src/components/SidebarV2/SidebarItem/SidebarItem.tsx
packages/fuselage/src/components/Sidepanel/Sidepanel.stories.tsx
packages/fuselage/src/components/Sidepanel/Sidepanel.styles.scss
packages/fuselage/src/components/Sidepanel/__snapshots__/Sidepanel.spec.tsx.snap

fix(fuselage): `SidebarV2Item` padding
